/**
 * Dados da grade — EM (UNIPAMPA Alegrete).
 * Ementas e objetivos separados, CH alinhada ao ementário oficial (PPC 2023).
 * Semestragem e pré-requisitos conforme matriz curricular.
 */
(function () {
  'use strict';
  const CCCG_EMENTA =
    'Componente Curricular Complementar de Graduação. Consulte a oferta semestral do curso.';

  const disciplines = [
    {
      id: 'calc1',
      name: 'Cálculo I',
      sem: 1,
      prereqs: [],
      codigo: 'AL0363',
      ch: '90h',
      ch_teo: 90,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Revisão de Matemática Básica. Noções básicas de conjuntos. A reta real. Intervalos e desigualdades. Funções de uma variável. Limites. Continuidade. Derivadas. Regras de derivação. Regra da cadeia. Derivação implícita. Diferencial. Regra de L’Hôpital, máximos e mínimos e outras aplicações.",
      objetivo: "Compreender e aplicar as técnicas do Cálculo Diferencial e Integral para funções reais de uma variável real, dando ênfase às suas aplicações.",
    },
    {
      id: 'geom',
      name: 'Geometria Analítica',
      sem: 1,
      prereqs: [],
      codigo: 'AL0002',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Vetores no plano e no espaço. Retas no plano e no espaço. Estudo do plano. Distância, área e volume. Cônicas, Quádricas.",
      objetivo: "Desenvolver noções e conhecimento sobre vetores, curvas, e superfícies no plano e no espaço.",
    },
    {
      id: 'fis1',
      name: 'Física I',
      sem: 1,
      prereqs: [],
      codigo: 'AL0003',
      ch: '75h',
      ch_teo: 60,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Movimento retilíneo. Movimento no plano. Leis de Newton. Trabalho e energia cinética. Energia potencial e conservação de energia. Quantidade de movimento linear e choque. Rotação de corpos rígidos. Gravitação.",
      objetivo: "Identificar fenômenos naturais em termos de quantidade e regularidade, bem como interpretar princípios fundamentais que generalizam as relações entre eles e aplicá-los na resolução de problemas simples da mecânica clássica.",
    },
    {
      id: 'intro_em',
      name: 'Introdução à Engenharia Mecânica',
      sem: 1,
      prereqs: [],
      codigo: 'AL0465',
      ch: '30h',
      ch_teo: 30,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "A Engenharia Mecânica, sua formação, capacitação e habilidades. Sua participação em entidades científicas e profissionais. Conceitos Básicos na Participação no mercado de trabalho: Empreendedor, Pesquisador, Prestador de serviço e engenheiro mecânico. Disseminação da cultura científica e tecnológica. Comunicação e Expressão. Normatização. Metodologias e Ferramentas de simulação científica e tecnológica.",
      objetivo: "Conhecer as metodologias de aquisição de conhecimento científico e suas principais formas de transmissão. Conhecer a estrutura do curso de Engenharia Mecânica, sua inserção no mercado de trabalho e suas entidades representativas e regulamentadoras.",
    },
    {
      id: 'dt',
      name: 'Desenho Técnico',
      sem: 1,
      prereqs: [],
      codigo: 'AL0007',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução ao desenho técnico. Desenho arquitetônico. Introdução ao desenho projetivo. Desenho em perspectiva, Traçados em 3D.",
      objetivo: "Utilizar o desenho técnico como linguagem técnica de comunicação, conforme as técnicas normalizadas pela ABNT.",
    },
    {
      id: 'quim',
      name: 'Química Geral e Experimental',
      sem: 1,
      prereqs: [],
      codigo: 'AL0366',
      ch: '45h',
      ch_teo: 30,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Atomística. Ligações químicas. Quantidade de matéria. Fórmulas químicas. Equações químicas. Estequiometria das reações. Reações químicas. Parte experimental.",
      objetivo: "Conhecer e aplicar conceitos básicos de Química Geral teórica e experimental.",
    },
    {
      id: 'alg',
      name: 'Algoritmos e Programação',
      sem: 1,
      prereqs: [],
      codigo: 'AL0005',
      ch: '60h',
      ch_teo: 30,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Noções de lógica de programação; Dados, expressões e algoritmos sequenciais; Estruturas de controle; Estruturas complexas; Modularização.",
      objetivo: "Desenvolver o raciocínio lógico aplicado à solução de problemas em nível computacional, além de introduzir os conceitos básicos de desenvolvimento de algoritmos, de forma a propiciar uma visão crítica e sistemática sobre resolução de problemas e prepará-lo para a atividade de programação.",
    },
    {
      id: 'eletrot',
      name: 'Eletrotécnica',
      sem: 2,
      prereqs: [],
      codigo: 'AL0006',
      ch: '45h',
      ch_teo: 30,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Critérios de segurança no laboratório e segurança em trabalhos com eletricidade. Modelo de preparação dos relatórios. Elementos e Leis de circuitos elétricos: análise em regime permanente. Equipamentos básicos de eletricidade: voltímetro, amperímetro, wattímetro, osciloscópio. Noções de acionamento de motores elétricos. Noções de instalações elétricas residenciais.",
      objetivo: "Identificar e utilizar corretamente os principais equipamentos para efetuar medições de tensão, corrente e potência. Aprender noções básicas de segurança com eletricidade e evitar os principais riscos de choque elétrico. Verificar conceitos fundamentais para acionamento de um motor elétrico CA.",
    },
    {
      id: 'alg_lin',
      name: 'Álgebra Linear',
      sem: 2,
      prereqs: [],
      codigo: 'AL0009',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Matrizes. Determinantes. Sistemas lineares. Espaços Vetoriais. Espaços com produto interno. Transformações Lineares. Autovalores e autovetores. Diagonalização de operadores.",
      objetivo: "Compreender os conceitos básicos relativos aos sistemas de equações lineares, suas operações e propriedades existentes. Desenvolver o raciocínio matemático, abstração e visualização de vetores, espaços vetoriais e suas operações no plano e no espaço. Operar com sistemas de equações lineares, espaços vetoriais, produtos, transformações lineares, autovalores e espaços com produto interno",
    },
    {
      id: 'calc2',
      name: 'Cálculo II',
      sem: 2,
      prereqs: ["calc1"],
      codigo: 'AL0010',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Integral indefinida e técnicas de integração; Integral definida; O teorema fundamental do cálculo; Integral imprópria. Aplicações do cálculo integral: cálculo de áreas, cálculo de volumes por rotação e invólucro cilíndrico, comprimento de arco, sistema de coordenadas polares e área de uma região em coordenadas polares; Funções de várias variáveis reais; Derivação parcial; Gradiente e derivadas direcionais.",
      objetivo: "Dominar técnicas fundamentais do cálculo diferencial e integral para funções reais de uma variável real, possibilitando a capacitação para a resolução de problemas aplicados em diversos campos da ciência e da engenharia. Compreender os conceitos de limite e diferenciabilidade para funções de várias variáveis, viabilizando um melhor entendimento das suas aplicações.",
    },
    {
      id: 'fis2',
      name: 'Física II',
      sem: 2,
      prereqs: ["calc1"],
      codigo: 'AL0011',
      ch: '75h',
      ch_teo: 60,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Oscilações. Ondas. Temperatura. Primeira e Segunda Lei da Termodinâmica. Teoria cinética dos gases. Hidrostática. Hidrodinâmica.",
      objetivo: "Distinguir entre os fenômenos físicos de oscilações e ondas. Compreender a diferença entre calor e temperatura; Aplicar e manipular equações para resolução de problemas; Relacionar os princípios físicos estudados às aplicações práticas da engenharia.",
    },
    {
      id: 'dm1',
      name: 'Desenho Mecânico I',
      sem: 2,
      prereqs: ["dt"],
      codigo: 'AL0033',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Normas de Desenho Técnico Mecânico. Desenho Projetivo. Desenho de Elementos de Máquinas e Conjuntos Mecânicos.",
      objetivo: "Utilizar o desenho técnico como linguagem técnica de comunicação, conforme as técnicas normalizadas pela ABNT.",
    },
    {
      id: 'mat_eng',
      name: 'Ciência e Engenharia de Materiais',
      sem: 2,
      prereqs: ["quim"],
      codigo: 'AL0175',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Diagramas de fases isomorfos; Diagramas de fases binários; Diagrama Fe-Fe3C, reações eutetóides e eutéticas; Aços e ferros fundidos; Ligas não-ferrosas; Ensaios Mecânicos: caracterização e ensaios não destrutivos; Mecanismos de fratura.",
      objetivo: "Adquirir o conhecimento básico sobre microestrutura e comportamento mecânico dos materiais de construção mecânica.",
    },
    {
      id: 'mec_ger',
      name: 'Mecânica Geral',
      sem: 2,
      prereqs: ["geom","fis1"],
      codigo: 'AL0015',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Princípios da estática. Sistemas de forças em equilíbrio; Equilíbrio de partículas e de corpos rígidos; Esforços internos solicitantes em vigas isostáticas; Centro de gravidade e centro da massa; Momento de inércia e produto de inércia.",
      objetivo: "Desenvolver habilidades para reconhecer os esforços solicitados em estruturas e determinar as características geométricas das seções.",
    },
    {
      id: 'termo1',
      name: 'Termodinâmica I',
      sem: 3,
      prereqs: ["calc2","fis2"],
      codigo: 'AL0075',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução à termodinâmica, e suas aplicações em engenharia. Propriedades das substâncias puras. Primeira e segunda Lei da Termodinâmica para massas e volumes de controle. Aplicação da termodinâmica para processos estacionários e transientes. Formas de transferência de calor. Ciclos de potência e de refrigeração.",
      objetivo: "Compreender os conceitos básicos e o funcionamento dos principais equipamentos das ciências térmicas. Aplicar as leis da conservação da massa, de energia e entropia. Analisar ciclos de potência e refrigeração com as suas variações.",
    },
    {
      id: 'dm_comp',
      name: 'Desenho Mecânico Computacional',
      sem: 3,
      prereqs: ["dm1"],
      codigo: 'AL0192',
      ch: '60h',
      ch_teo: 30,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução e histórico. Conceitos gerais de desenho assistido por computador (CAD). Geração de padrões e templates. Criação de sketches e modelagem de peças. Recursos e técnicas para otimização e agilidade no desenho. Montagens. Reparos e alterações no desenho.",
      objetivo: "Adquirir conceitos e fundamentos do uso do CAD em engenharia mecânica, desenvolvendo habilidades para a modelagem tridimensional e criação de folhas de representações técnicas.",
    },
    {
      id: 'eq_dif1',
      name: 'Equações Diferenciais I',
      sem: 3,
      prereqs: ["alg_lin","calc2"],
      codigo: 'AL0019',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Conceito e classificação de Equações diferenciais. Tipos de soluções. Equações diferenciais de primeira ordem. Equações diferenciais de segunda ordem. Equações lineares de ordem superior. Sistemas lineares de equações diferenciais.",
      objetivo: "Desenvolver conceitos matemáticos relacionados às equações diferenciais. Aplicar os conceitos da componente curricular em problemas de engenharia. Compreender/interpretar os resultados obtidos. Adotar a técnica de resolução de equação diferencial que melhor se adapta ao problema proposto.",
    },
    {
      id: 'calc3',
      name: 'Cálculo III',
      sem: 3,
      prereqs: ["calc2"],
      codigo: 'AL0020',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Integrais duplas (coordenadas polares) e triplas (sistemas de coordenadas cartesianas, cilíndricas e esféricas). Funções vetoriais. Campos vetoriais. Integrais curvilíneas. Operadores divergentes e rotacional. Teorema de Green. Integrais de superfície. Teoremas de Gauss e Stokes.",
      objetivo: "Compreender os conceitos de integração para funções de várias variáveis, bem como suas aplicações. Compreender e aplicar os conceitos de derivada e integral de funções vetoriais e aplicar os teoremas da divergência e Stokes em alguns casos particulares.",
    },
    {
      id: 'fis3',
      name: 'Física III',
      sem: 3,
      prereqs: ["calc2"],
      codigo: 'AL0021',
      ch: '75h',
      ch_teo: 60,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Lei de Coulomb. Campo elétrico. Potencial eletrostático. Capacitância e capacitores. Dielétricos. Corrente elétrica. Campo magnético. Lei de Ampère. Lei de indução. Indutância e indutores.",
      objetivo: "Conhecer e interpretar os fenômenos físicos relacionados a eletricidade e magnetismo a partir da teoria eletromagnética.",
    },
    {
      id: 'res_mat1',
      name: 'Resistência dos Materiais I',
      sem: 3,
      prereqs: ["mec_ger"],
      codigo: 'AL0375',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Tensão, Deformação, Propriedades Mecânicas dos Materiais; Carga Axial, Torção, Flexão, Cisalhamento Transversal.",
      objetivo: "Determinar e compreender as tensões e deformações resultantes dos esforços internos solicitantes.",
    },
    {
      id: 'ofic',
      name: 'Oficina de Práticas Mecânicas',
      sem: 3,
      prereqs: [],
      specialMinCH: 300,
      codigo: 'AL0474',
      ch: '30h',
      ch_teo: 0,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 15,
      ementa: "Estruturação de práticas de engenharia mecânica no formato de oficinas, a fim de proporcionar subsídios para que os discentes realizem ações extensionistas para a comunidade e/ou instituições externas, vinculadas a programas/projetos institucionais ligados à área temática do Trabalho.",
      objetivo: "Desenvolver atividades de extensão que possibilitem uma maior interação transformadora entre a UNIPAMPA e a sociedade, por meio da produção e da aplicação do conhecimento, em articulação permanente com o ensino e a pesquisa.",
    },
    {
      id: 'probest',
      name: 'Probabilidade e Estatística',
      sem: 4,
      prereqs: ["calc2"],
      codigo: 'AL0022',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Estatística Descritiva. Teoria das Probabilidades. Distribuições Discretas de Probabilidades. Distribuições Contínuas de Probabilidades. Teoria da Amostragem. Estimação de Parâmetros. Testes de Hipótese. Correlação e Regressão.",
      objetivo: "Ter um sólido conhecimento sobre cálculo de probabilidade, variáveis aleatórias, processos aleatórios e estatística.",
    },
    {
      id: 'metro',
      name: 'Metrologia',
      sem: 4,
      prereqs: ["dm1"],
      codigo: 'AL0034',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Conceitos Fundamentais de Metrologia e Instrumentação; Tolerância e Ajustes; Controle Dimensional; Tolerância Geométrica; Instrumentos de Controle Geométrico; Rugosidade Superficial; Atividade Prática Pertinente a cada item anterior.",
      objetivo: "Aplicar os princípios básicos envolvidos na realização das medições, como o controle dimensional e geométrico, o princípio de funcionamento e a seleção dos instrumentos para as medições de distâncias, de ângulos e de irregularidades micro geométricas das superfícies das peças mecânicas.",
    },
    {
      id: 'calc_num',
      name: 'Cálculo Numérico',
      sem: 4,
      prereqs: ["calc2","alg"],
      codigo: 'AL0037',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Erros. Zeros de Funções e Polinômios. Aproximações de Funções. Interpolação Numérica. Integração Numérica. Sistemas Lineares. Resolução Numérica de Equações Diferenciais Ordinárias. Apoio Computacional.",
      objetivo: "Desenvolver noções sobre o funcionamento e uso de métodos numéricos básicos úteis para a resolução de problemas modelados por equações algébricas ou diferenciais.",
    },
    {
      id: 'maq_op',
      name: 'Máquinas Operatrizes',
      sem: 4,
      prereqs: ["dm1"],
      codigo: 'AL0053',
      ch: '45h',
      ch_teo: 30,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Conceitos Iniciais das Máquinas Operatrizes, Técnicas de Fabricação, Acionamento das Máquinas Operatrizes, Técnicas de Comando em Máquinas Operatrizes, Características construtivas das máquinas operatrizes.",
      objetivo: "Desenvolver habilidades relativas aos diversos processos existentes, relacionando custo, qualidade, rapidez e segurança na escolha da ferramenta e do processo.",
    },
    {
      id: 'lab_met',
      name: 'Laboratório de Metalografia e Ensaios Mecânicos',
      sem: 4,
      prereqs: ["mat_eng"],
      codigo: 'AL0054',
      ch: '30h',
      ch_teo: 0,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Análise microestrutural de metais e correlação com os respectivos diagramas de fases. Aços, ferros fundidos e ligas não-ferrosas. Ensaios Mecânicos: Mecanismos de fratura. Ensaios não destrutivos.",
      objetivo: "Desenvolver habilidades para a especificação, realização e interpretação de testes para a caracterização metalúrgica e mecânica de materiais.",
    },
    {
      id: 'mec_flu',
      name: 'Mecânica dos Fluidos',
      sem: 4,
      prereqs: ["fis2","eq_dif1"],
      codigo: 'AL0078',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Caracterização dos fluidos: propriedades físicas relevantes. Estática dos fluidos. Equações integrais do movimento. Análise Diferencial dos movimentos dos fluidos. Escoamento incompressível de fluidos invíscidos. Análise dimensional e semelhança. Escoamento laminar completamente desenvolvido. Escoamento em tubos e dutos. Camada limite. Escoamento de fluidos ao redor de corpos submersos.",
      objetivo: "Compreender o comportamento de superfícies e de corpos parcial ou totalmente submersos num fluido. Compreender e aplicar as equações da conservação da massa, da energia e da quantidade de movimento pela análise integral e diferencial em escoamentos plenamente desenvolvidos e incompressíveis. Aplicar os principais grupos adimensionais na análise por semelhança em problemas de engenharia.",
    },
    {
      id: 'res_mat2',
      name: 'Resistência dos Materiais II',
      sem: 4,
      prereqs: ["res_mat1"],
      codigo: 'AL0381',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Cargas Combinadas, Transformações de tensão, Transformação da Deformação, Teoria de Falha; Projeto de Vigas e Eixos; Deflexão de Vigas e Eixos; Flambagem de Colunas; Métodos de Energia.",
      objetivo: "Compreender o estado de tensões e deformações, projeto de vigas e eixos de transmissão, deflexão de vigas e flambagem de colunas.",
    },
    {
      id: 'termo_ap',
      name: 'Termodinâmica Aplicada',
      sem: 4,
      prereqs: ["termo1"],
      codigo: 'AL0466',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Combustão homogênea estequiométrica e incompleta; Sistema de potência a gás: ciclos Otto, Diesel, Sabathé, Atkinson e Brayton; Sistemas de potência com mudança de fase: Ciclos de Rankine simples, com reaquecimento, regenerativos e com cogeração.",
      objetivo: "Conhecer as características dos principais ciclos ideais de máquinas térmicas motoras; Dominar os princípios fundamentais da combustão completa e incompleta de misturas combustíveis.",
    },
    {
      id: 'dinam',
      name: 'Dinâmica',
      sem: 5,
      prereqs: ["mec_ger"],
      codigo: 'AL0055',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Cinemática da partícula; Cinética da partícula: Segunda lei de Newton; Método da energia e da quantidade de movimento; Sistema das partículas; Cinemática dos corpos rígidos; Cinética dos corpos rígidos em movimento plano; Movimento plano dos corpos rígidos: energia e da quantidade de movimento;",
      objetivo: "Adquirir conhecimentos teóricos básicos de dinâmica da partícula e do corpo rígido, necessários para o entendimento da cinemática e dinâmica dos elementos móveis de máquinas.",
    },
    {
      id: 'mecan',
      name: 'Mecanismos',
      sem: 5,
      prereqs: ["mec_ger","calc2"],
      codigo: 'AL0074',
      ch: '30h',
      ch_teo: 30,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Conceitos relativos ao estudo dos mecanismos: Introdução, tipos de mecanismos. Análise de posição e movimento. Análise de velocidades. Análise de Acelerações. Estudo dos cames.",
      objetivo: "Adquirir conhecimentos básicos de mecanismos, desenvolvendo habilidades para modelagem e análise de mecanismos, máquinas, equipamentos e sistemas mecânicos em geral que possuam movimento alternado, rotativo ou periódico.",
    },
    {
      id: 'usinag',
      name: 'Usinagem',
      sem: 5,
      prereqs: ["maq_op","mat_eng"],
      codigo: 'AL0076',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Movimentos e relações geométricas; mecanismo de formação do cavaco; forças e potências de corte; materiais para ferramentas; avarias; desgastes e vida da ferramenta, fluídos de corte; condições econômicas mínimo custo, máxima produção; usinabilidade; atividades de laboratório.",
      objetivo: "Conhecer os diversos processos existentes, relacionando custos, qualidades, rapidez e segurança na decisão e aplicação do processo, e contribuindo em novos projetos e ferramentas para o processo.",
    },
    {
      id: 'maq_flu',
      name: 'Máquinas de Fluido',
      sem: 5,
      prereqs: ["mec_flu"],
      codigo: 'AL0136',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Máquinas de Fluido: Definições, Nomenclatura e Classificação; Equações Fundamentais; Bombas Centrífugas: Perdas e Rendimento; Análise Dimensional e Semelhança; Cavitação e Choque Sônico; Bombas de Deslocamento Positivo.",
      objetivo: "Conhecer as características de cada tipo de máquina de fluido, bem como as equações fundamentais e suas possíveis simplificações, a fim de usá-las no projeto e/ou escolha para cada aplicação particular.",
    },
    {
      id: 'trat_term',
      name: 'Tratamentos Térmicos e Superficiais',
      sem: 5,
      prereqs: ["lab_met"],
      codigo: 'AL0176',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Aços e ferros fundidos. Diagrama de equilíbrio fe-fe3c. Diagramas de resfriamento contínuo e diagramas isotérmicos. Tratamentos térmicos e termoquímicos dos aços e ligas ferrosas. Tratamentos térmicos de ligas não ferrosas. Tratamentos superficiais: pvd, shot peening e outros.",
      objetivo: "Desenvolver habilidades para especificação e realização de tratamentos térmicos e termoquímicos de aços, ferros fundidos e ligas não ferrosas com vistas a obter propriedades mecânicas específicas.",
    },
    {
      id: 'frat',
      name: 'Mecânica da Fratura e Fadiga',
      sem: 5,
      prereqs: ["res_mat2"],
      codigo: 'AL0467',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Defeitos dos Cristais e Trincas Macroscópicas; Teoria de Griﬀith e Taxa de Liberação de Energia (G) na propagação de trincas; Campo Elástico em Torno das Pontas de Trincas; Fator de Intensidade de Tensão (K); Relação entre K e G; Tenacidade de Fratura de Materiais; Integral-J; Zona Plástica em Torno das Pontas de Trincas; Critérios de Propagação de Trincas; Métodos de Medição de Tenacidade de Fratura; Fenômeno da fadiga; Resistência à fadiga dos materiais; Resistência à fadiga dos componentes; Método (S-N); Efeito das solicitações médias; Teoria dos danos acumulados; Propagação de trincas de fadiga.",
      objetivo: "Desenvolver habilidades para o dimensionamento e identificação de causas de falha de componentes e estruturas mecânicas na possível presença de defeitos (trincas) e também levando em conta sua danificação em serviço (fadiga).",
    },
    {
      id: 'transf',
      name: 'Transferência de Calor e Massa',
      sem: 5,
      prereqs: ["mec_flu","calc3"],
      codigo: 'AL0098',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Condução: condutividade térmica, equação geral da condução em regime permanente e transiente. Convecção: coeficiente de transferência de calor, variáveis que influenciam o coeficiente de transferência de calor, aletas, convecção natural, convecção forçada, transferência de calor entre sólidos e fluidos, escoamento no interior de tubos. Radiação: incidência de energia radiante, emissividade, corpo negro. Conceitos e equações básicas de transferência de massa.",
      objetivo: "Compreender e aplicar as equações governantes dos mecanismos de transferência de calor por condução, convecção e radiação térmica. Compreender e aplicar os principais números adimensionais das camadas-limites hidrodinâmica, térmica e de concentração na resolução dos problemas de transferência de calor por convecção natural e forçada.",
    },
    {
      id: 'conform',
      name: 'Conformação Mecânica',
      sem: 6,
      prereqs: ["res_mat1","trat_term"],
      codigo: 'AL0118',
      ch: '60h',
      ch_teo: 30,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Considerações gerais dos processos de fabricação por conformação mecânica. Tensões. Deformações. Velocidade de deformação. Plasto mecânica. Curva de escoamento. Teoria Elementar da Plasticidade. Teoria do Limite Superior. Laminação. Trefilação. Forjamento. Embutimento. Extrusão. Conformação de sinterizados. Processos especiais.",
      objetivo: "Desenvolver a capacidade de elaborar, interpretar e executar processos de fabricação aplicando os processos de conformação mecânica. Conhecer os diversos processos existentes, relacionando custos, qualidades, rapidez e segurança na decisão e aplicação dos mesmos.",
    },
    {
      id: 'vibr',
      name: 'Vibrações de Sistemas Mecânicos',
      sem: 6,
      prereqs: ["dinam","eq_dif1"],
      codigo: 'AL0194',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Movimento Oscilatório, Vibração Livre, Movimento Excitado Harmonicamente, Sistemas de Dois Graus de Liberdade, Sistema com Vários Graus de Liberdade, Equações de Lagrange.",
      objetivo: "Capacitar-se para a modelagem de sistemas mecânicos e controle das suas vibrações para diferentes tipos de excitações.",
    },
    {
      id: 'sist_prod',
      name: 'Sistemas de Produção',
      sem: 6,
      prereqs: ["maq_op"],
      codigo: 'AL0196',
      ch: '60h',
      ch_teo: 30,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução à administração da produção. Planejamento da capacidade. Decisões sobre localização de fábrica. Projeto do produto, planejamento e análise de processos. Arranjo físico de instalações. Projeto e medida do trabalho.",
      objetivo: "Desenvolver habilidades e competências capazes de analisar criticamente o sistema de produção e de operações de qualquer organização industrial ou de serviços.",
    },
    {
      id: 'maq_el',
      name: 'Tópicos de Máquinas Elétricas',
      sem: 6,
      prereqs: ["eletrot","fis3"],
      codigo: 'AL0221',
      ch: '30h',
      ch_teo: 30,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "O Sistema Elétrico: Geração Transmissão; Distribuição; Energização versus Eletrificação Rural; Legislação e Tarifas de Energia Elétrica; Transformadores: Monofásicos; Trifásicos; Aplicações; Especificação; Condições Operacionais; Máquinas Elétricas: Corrente Contínua e Alternada; Aplicações; Especificações; Proteção; Controle; Aplicações de Energia Elétrica em Sistemas e Processos de Uso Final.",
      objetivo: "Adquirir um embasamento prático para desenvolvimento de projetos elétricos que atendam aos requisitos dos serviços energéticos de uso final nos diferentes segmentos socioeconômicos.",
    },
    {
      id: 'eng_eco',
      name: 'Introdução à Engenharia Econômica',
      sem: 6,
      prereqs: ["probest"],
      codigo: 'AL0380',
      ch: '45h',
      ch_teo: 15,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Fundamentos da matemática financeira. Análise de viabilidade econômica de projetos de investimentos.",
      objetivo: "Obter conhecimentos, do campo da engenharia econômica, para possibilitar a adequada tomada de decisão na análise de projetos de investimentos.",
    },
    {
      id: 'refrig',
      name: 'Refrigeração e Ar condicionado',
      sem: 6,
      prereqs: ["termo_ap","transf"],
      codigo: 'AL0471',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Psicrometria. Conforto térmico. Carga térmica de ar condicionado. Ventilação natural e forçada. Difusão de ar. Dutos de distribuição de ar. Ciclos de refrigeração por compressão de vapor e absorção. Sistemas de ar condicionado.",
      objetivo: "Dimensionar a carga térmica de verão e de inverno de um ambiente, visando à avaliação do conforto térmico, à seleção da máquina de ar-condicionado e o cálculo da perda de carga da rede de dutos e difusores. Compreender e aplicar o equacionamento e os diagramas dos ciclos de refrigeração por compressão de vapor e de absorção para a seleção de sistemas de ar condicionado.",
    },
    {
      id: 'elem_maq1',
      name: 'Elementos de Máquina I',
      sem: 6,
      prereqs: ["frat","trat_term"],
      codigo: 'AL0096',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Projeto de eixos e árvores, Projeto e seleção de acoplamentos, chavetas, estrias e mancais, uniões aparafusadas, uniões soldadas, molas, lubrificantes e lubrificação.",
      objetivo: "Construir a base teórica e prática que permita a elaboração de projetos, de análises e de especificação/seleção de elementos mecânicos e partes de máquinas.",
    },
    {
      id: 'elem_maq2',
      name: 'Elementos de Máquinas II',
      sem: 7,
      prereqs: ["res_mat2"],
      codigo: 'AL0117',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Transmissões mecânicas. Transmissão por engrenagens, transmissão por correntes, transmissão por correias, transmissão por atrito.",
      objetivo: "Desenvolver base teórica e prática que permita a elaboração de projetos, de análises e de especificação/seleção de transmissão mecânica de potência, bem como de seus elementos.",
    },
    {
      id: 'hid_pneu',
      name: 'Sistemas Hidráulicos e Pneumáticos',
      sem: 7,
      prereqs: ["mec_flu","maq_el"],
      codigo: 'AL0099',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução ao estudo da hidráulica, fluidos hidráulicos, reservatórios e acessórios, filtros, cilindros, bombas, válvulas, pneumática, conceitos e princípios básicos, produção e distribuição do ar comprimido, atuadores pneumáticos, válvulas de comando, funções lógicas, projeto de comandos combinatórios e sequenciais.",
      objetivo: "Proporcionar o conhecimento dos aspectos conceituais, a simbologia geral, os esquemas de instalação pneumática com domínio dos acessórios, diferenciar diagramas de fase e explorar os aspectos de automação pneumática e hidráulica.",
    },
    {
      id: 'cam',
      name: 'Manufatura Assistida por Computador',
      sem: 7,
      prereqs: ["dm_comp","usinag"],
      codigo: 'AL0468',
      ch: '60h',
      ch_teo: 30,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Técnicas de manufatura assistida por computador (CAM). Processos de fabricação robotizados e com controle numérico computadorizado usando centros de usinagem, fresadoras e tornos. Programação ISO.",
      objetivo: "Aplicar as técnicas de manufatura assistida por computador. Implementar interface computador/máquina operatriz. Adquirir habilidades para utilizar, especificar e implantar processos de fabricação robotizados com uso de controle numérico computadorizado.",
    },
    {
      id: 'sold',
      name: 'Soldagem',
      sem: 7,
      prereqs: ["trat_term"],
      codigo: 'AL0469',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Conceitos Fundamentais, simbologia da soldagem, consumíveis de soldagem, processos de soldagem (soldagem por eletrodo revestido, soldagem TIG, MIG, MAG, soldagem com gás, processos não convencionais), tipos de juntas, metalurgia da soldagem, Inspeção em soldagem. Dimensionamento de juntas soldadas. Estudo de normas, códigos e recomendações para o projeto de juntas soldadas.",
      objetivo: "Compreender os conceitos fundamentais da Soldagem e sua relação com as aplicações em diversos materiais para engenharia; Obter uma base dos diversos processos de soldagem usados em Engenharia sob a óptica teórica e prática. Desenvolver a conduta de especificação, planejamento e aplicação, dos processos de soldagem, regulagem e operação dos equipamentos mais comuns em soldagem.",
    },
    {
      id: 'met_proj',
      name: 'Metodologia de Projeto de Produto',
      sem: 7,
      prereqs: ["conform"],
      codigo: 'AL0470',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Planejamento Estratégico, Planejamento de Produto, Planejamento de Projeto, Projeto Informacional e Projeto Conceitual",
      objetivo: "Desenvolver competências para planejar estrategicamente na corporação, planejar taticamente o produto, planejar os recursos de projeto e operacionalizar o projeto informacional e conceitual de um produto.",
    },
    {
      id: 'cccg7',
      name: 'CCCG',
      sem: 7,
      cat: 'em_cccg',
      prereqs: [],
      codigo: '—',
      ch: '60h',
      ementa: CCCG_EMENTA,
    },
    {
      id: 'leg_et',
      name: 'Legislação, Ética e Exercício Profissional de Engenharia',
      sem: 8,
      prereqs: ["intro_em"],
      codigo: 'AL0142',
      ch: '30h',
      ch_teo: 30,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Fundamentos e conceituação filosófica de moral, ética e valores. Ética, moral e valores sociais, ambientais e econômicos. Código de Ética Profissional do engenheiro; Legislação Profissional - CONFEA/CREAs. Responsabilidade Técnica - Código de Defesa do Consumidor. Propriedade Intelectual. Direitos Autorais. Transferência de tecnologia concorrência desleal - abuso de poder econômico. Acervo técnico. Atribuições profissionais.",
      objetivo: "Conhecer acerca das responsabilidades técnicas e civis, numa perspectiva da ética e do exercício profissional, no papel de sujeitos participantes das mudanças socioeconômicas.",
    },
    {
      id: 'ctrl_mec',
      name: 'Controle de Sistemas Mecânicos',
      sem: 8,
      prereqs: ["vibr"],
      codigo: 'AL0215',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução aos sistemas de controle. A transformada de Laplace. Modelagem matemática de sistemas mecânicos. Análise da resposta transitória. Ações básicas de controle e resposta de sistemas de controle. Análise do lugar geométrico das raízes.",
      objetivo: "Adquirir as noções fundamentais e os instrumentos necessários para a análise de sistemas mecânicos dinâmicos, e para o projeto de dispositivos que possam ser utilizados para modificar a dinâmica para responder às especificações de funcionamento.",
    },
    {
      id: 'adm',
      name: 'Administração',
      sem: 8,
      prereqs: ["eng_eco"],
      codigo: 'AL0394',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Fundamentos da administração. O administrador. Partes da administração. Planejamento da ação empresarial.",
      objetivo: "Entender a natureza da gestão empresarial e os sistemas produtivos; conhecer técnicas, ferramentas e metodologias administrativas que podem ser aplicadas na gestão e na tomada de decisão diante da produção de bens e execução de serviços.",
    },
    {
      id: 'fundicao',
      name: 'Fundição',
      sem: 8,
      prereqs: ["trat_term"],
      codigo: 'AL0472',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Aspectos tecnológicos e econômicos dos processos de fundição em moldes de areia, cerâmicas e coquilhas. Propriedades dos metais fundidos. Projeto de peças. Fundamentos da solidificação dos metais, nucleação homogênea e heterogênea, crescimentos de metais puros e ligas metálicas, super resfriamento constitucional, rechupes e massalotes, defeitos de fundição. Análise de microestruturas de fundidos, análise dimensional, acabamento superficial. Verificação das propriedades mecânicas.",
      objetivo: "Avaliar a viabilidade tecnológica e econômica, possibilitando o planejamento, especificação e seleção dos processos metalúrgicos de fabricação, em aplicações de engenharia de maneira técnica e objetiva.",
    },
    {
      id: 'proj_int1',
      name: 'Projeto Integrado I',
      sem: 8,
      prereqs: ["met_proj","elem_maq2"],
      codigo: 'AL0473',
      ch: '150h',
      ch_teo: 0,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 150,
      ementa: "O discente deverá cumprir a carga de extensão atuando como membro da equipe executora de um projeto vinculado a uma demanda de programa/projeto institucional de extensão ligado à área temática de Tecnologia e Produção, executando as etapas de: Introdução ao processo de projeto de produtos industriais; Desenvolvimento das especificações de projeto; Geração e seleção de concepções; Configuração do produto; Avaliação de possibilidades de inovação, considerando noções sobre propriedade industrial, desenvolvimento de patentes e empreendedorismo; Detalhamento do projeto do produto; Encerramento do projeto.",
      objetivo: "Aplicar os conhecimentos obtidos nos componentes curriculares cursados durante o curso da engenharia mecânica para elaboração de uma solução para um problema apresentado pela comunidade externa. O projeto será criado com a supervisão de professor(es) orientador(es).",
    },
    {
      id: 'cccg8',
      name: 'CCCG',
      sem: 8,
      cat: 'em_cccg',
      prereqs: [],
      codigo: '—',
      ch: '45h',
      ementa: CCCG_EMENTA,
    },
    {
      id: 'gest_qual',
      name: 'Sistemas e Gestão de Qualidade',
      sem: 9,
      prereqs: ["metro","sist_prod"],
      codigo: 'AL0116',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Histórico e evolução da qualidade; O que é qualidade; Pensadores da Qualidade; Ferramentas de qualidade (5S, GQT, Fluxograma ou diagrama de processo, Folha de verificação, Estratificação, Diagrama de pareto, Diagrama de causa e efeito, Histograma, Diagrama de dispersão, CEP, Gráfico de controle, MASP). Programas e Certificações da qualidade (ISO 9000, ISO 14000, PGQP, PNQ, OSHAS 18001 (Occupational Health & Safety Management System)).",
      objetivo: "Desenvolver uma visão geral sobre o movimento de qualidade a nível global e utilizar com habilidade as principais ferramentas de qualidade.",
    },
    {
      id: 'tcc1',
      name: 'Trabalho de Conclusão de Curso I',
      sem: 9,
      prereqs: [],
      specialMinCH: 2400,
      codigo: 'AL0241',
      ch: '30h',
      ch_teo: 0,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Normatização de trabalhos científicos; Métodos científicos; Pesquisa bibliográfica; Elaboração do Projeto de Trabalho de Conclusão de Curso (projeto de TCC), projetual ou aplicativo, voltado para o estudo de um problema de engenharia específico, utilizando o referencial proporcionado pela teoria de engenharia, numa das áreas da engenharia Mecânica.",
      objetivo: "Elaborar um trabalho de caráter técnico-científico, voltado para o estudo de um problema de engenharia específico de sua área de atuação profissional, utilizando o referencial proporcionado pela teoria de engenharia.",
    },
    {
      id: 'gest_amb',
      name: 'Fundamentos da Gestão Ambiental',
      sem: 9,
      prereqs: [],
      codigo: 'AL0390',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Ambiente e desenvolvimento sustentável. Políticas Ambientais. Projetos ambientais.",
      objetivo: "Conhecer as principais definições, legislações e projetos ambientais requeridos, pertinentes aos projetos de engenharia que possam apresentar impactos ambientais.",
    },
    {
      id: 'proj_int2',
      name: 'Projeto Integrado II',
      sem: 9,
      prereqs: ["proj_int1"],
      codigo: 'AL0475',
      ch: '150h',
      ch_teo: 0,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 150,
      ementa: "O discente deverá cumprir a carga de extensão atuando como membro da equipe executora de um projeto vinculado a uma demanda de programa/projeto institucional de extensão ligado à área temática de Tecnologia e Produção, executando as etapas de: Desenvolvimento final de um produto ou solução para a comunidade externa; Desenvolvimento de um plano de negócios; Avaliação de possibilidades de inovação, considerando noções sobre propriedade industrial, desenvolvimento de patentes e empreendedorismo; Desenvolvimento e apresentação de um Projeto Integrado de Produto.",
      objetivo: "Aplicar os conhecimentos obtidos nos componentes curriculares cursados para elaboração de um projeto integrado de produto. Desenvolver a capacidade de especificar, implementar e testar projetos que envolvam conteúdos multidisciplinares e relacionados à área de Engenharia Mecânica, com aplicação direta na sociedade.",
    },
    {
      id: 'seg_trab',
      name: 'Segurança e Saúde no Trabalho',
      sem: 9,
      prereqs: [],
      codigo: 'AL0368',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução à segurança no trabalho. Legislação e normatização. EPI/EPC. Higiene e medicina do trabalho. Ergonomia. Segurança com a eletricidade. Proteção contra incêndios. Primeiros socorros.",
      objetivo: "Estudar as normas vigentes relativas à segurança, saúde, higiene e medicina no trabalho.",
    },
    {
      id: 'estagio',
      name: 'Estágio Supervisionado',
      sem: 10,
      prereqs: [],
      specialMinCH: 3330,
      codigo: 'AL0242',
      ch: '300h',
      ch_teo: 0,
      ch_prat: 300,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Execução de atividades de atribuição de Engenheiro Mecânico em instituições, empresas públicas civis ou militares, autárquicas, privadas ou de economia mista. Utilização dos conhecimentos adquiridos no curso na solução de problemas ou implantação de melhorias. Elaboração de relatório descrevendo as atividades desenvolvidas. Apresentação em sessão pública das atividades.",
      objetivo: "Adquirir experiências pré-profissionais que possibilitem a identificação de campos de atuação em futuras atividades profissionais, bem como ampliar o interesse pela pesquisa técnico-científica relacionada com problemas peculiares da Engenharia Mecânica.",
    },
    {
      id: 'tcc2',
      name: 'Trabalho de Conclusão de Curso II',
      sem: 10,
      prereqs: ["tcc1"],
      codigo: 'AL0159',
      ch: '30h',
      ch_teo: 0,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Elaboração de trabalho de caráter técnico científico, projetual ou aplicativo, que revele o domínio do tema escolhido e das competências definidas no perfil do egresso constantes neste PPC. Redação do trabalho em formato de monografia, conforme projeto aprovado na componente curricular de TCC I. Defesa do trabalho em sessão pública.",
      objetivo: "Sintetizar os conhecimentos e habilidades adquiridas ao longo do curso, através da elaboração de um trabalho de conclusão de curso com base em metodologia científica, apresentando-o para uma comissão examinadora.",
    },
  ];

  window.GRADE_CURSO_CONFIG = {
    sigla: 'em',
    title: "Grade Curricular \u2014 Engenharia Mec\u00e2nica",
    subtitle: "UNIPAMPA \u00b7 Campus Alegrete \u00b7 PPC 2023",
    maxSemesters: 10,
    disciplines,
    /** Plano de integralização (PPC 2023 — Tabela 1). */
    chIntegralization: {
      total: 3900,
      buckets: [
        {
          id: 'ccog',
          shortLabel: 'CCOG',
          label: 'Componentes curriculares obrigatórios de graduação (CCOGs)',
          required: 3615,
          source: 'mandatory',
        },
        {
          id: 'cccg',
          shortLabel: 'CCCG',
          label: 'Componentes curriculares complementares de graduação (CCCGs)',
          required: 105,
          source: 'cccg',
        },
        {
          id: 'acev',
          shortLabel: 'ACEV',
          label: 'Atividades curriculares de extensão vinculadas (ACEV)',
          required: 330,
          source: 'aceMandatory',
          countsTowardTotal: false,
        },
        {
          id: 'acee',
          shortLabel: 'ACEE',
          label: 'Atividades curriculares de extensão específicas (ACEE)',
          required: 75,
          manual: true,
        },
        {
          id: 'acg',
          shortLabel: 'ACG',
          label: 'Atividades complementares de graduação (ACGs)',
          required: 105,
          manual: true,
        },
      ],
    },
    cccgSemLimits: {
      7: 60,
      8: 45,
    },
    cccgs: [
      {
        codigo: "AL0056",
        nome: "Sistemas Hidráulicos e Térmicos",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["fis2"],
        ementa: "Fundamentos e princípios da termodinâmica. Máquinas térmicas e hidráulicas. Fontes convencionais e renováveis de energia elétrica. Centrais elétricas.",
        objetivo: "Especificar e projetar sistemas de geração de energia elétrica, baseados em fontes renováveis e não renováveis de energia, com ênfase particular aos sistemas hidrelétricos e termoelétricos.",
      },
      {
        codigo: "AL2072",
        nome: "Análise Experimental de Tensões",
        cat: 'em_cccg',
        ch: 45,
        ch_teo: 15,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["res_mat2"],
        ementa: "Comportamento tensão x deformação dos materiais. Teoria da elasticidade: medição de deformação e cálculo de tensões. Extensômetro de Resistência Elétrica: tipos e aplicações. Células de carga: tipos, aplicações, noções de projeto. Extensometria de resistência elétrica: fundamentos, ponte de Wheatstone, medições, tratamento do sinal, fontes de erro. Outras técnicas experimentais de análise de tensões. Tensões residuais e técnicas experimentais de análise.",
        objetivo: "Aprofundar conhecimentos na área de análise de tensões em estruturas e componentes mecânicos e desenvolver habilidades para análises experimentais.",
      },
      {
        codigo: "AL2121",
        nome: "Introdução à Dinâmica Veicular",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["dinam","elem_maq2"],
        ementa: "Pneus; Forças e acelerações em um veículo em operação; Transmissão de força pneu pista: Modelo quase estático; Mecânica da frenagem e freios; Balanço de potências; Diagramas de desempenho; Princípios de carrocerias aerodinâmicas; Estabilidade direcional; Sistema de direção; Suspensões planas.",
        objetivo: "Obter conhecimento geral, teórico e prático da dinâmica veicular.",
      },
      {
        codigo: "AL2190",
        nome: "Manutenção Mecânica",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["maq_flu","hid_pneu"],
        ementa: "Engenharia de manutenção: aspectos históricos, abordagem atual. Planejamento e gestão estratégica da manutenção. Técnicas para diagnóstico de falhas: termografia, vibrometria, lubrificação e análise de lubrificantes, ensaios não-destrutivos. Informatização da manutenção. Estudos de caso.",
        objetivo: "Desenvolver um olhar crítico a respeito das diferentes formas de manutenção mecânica presentes na atividade do engenheiro mecânico.",
      },
      {
        codigo: "AL2245",
        nome: "Análise Numérica e Experimental em Conformação Mecânica",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["conform","dm_comp"],
        ementa: "Modelo de cálculo simplificado de tensões e deformações para geometrias planas. Modelo de cálculo simplificado de tensões e deformações para geometrias axissimétricas. Modelo de cálculo baseado na Teoria Elementar da Plasticidade (TEP). Método de tiras. Método dos tubos. Método dos discos. Simulação computacional dos processos de conformação mecânica. Ensaios e experimentos em conformação mecânica.",
        objetivo: "Desenvolver e aprofundar a capacidade de modelar e calcular os esforços e deformações em processos diversos de conformação mecânica. Realizar simulações computacionais e executar ensaios e experimentos práticos em processos diversos de conformação mecânica.",
      },
      {
        codigo: "AL2073",
        nome: "Corrosão",
        cat: 'em_cccg',
        ch: 30,
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["lab_met"],
        ementa: "Termodinâmica e cinética eletroquímica. Fundamentos de corrosão. Formas de corrosão. Mecanismos básicos de corrosão, Passivação. Ensaios de corrosão. Metodologia eletroquímica para estudos de corrosão. Prevenção contra a corrosão. Métodos de combate à corrosão.",
        objetivo: "Aplicação dos conceitos de termodinâmica e cinética eletroquímica na compreensão e avaliação do processo corrosivo. Caracterizar as diferentes formas de corrosão e propor formas de prevenção.",
      },
      {
        codigo: "AL2074",
        nome: "Materiais Poliméricos e Compósitos",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["mat_eng"],
        ementa: "Materiais Poliméricos: Termoplásticos, Termorrígidos, Borrachas. Compósitos e suas principais aplicações.",
        objetivo: "Adquirir conhecimento básico sobre os polímeros e compósitos de maior aplicação na engenharia.",
      },
      {
        codigo: "AL2153",
        nome: "Ferros Fundidos e Ligas Leves",
        cat: 'em_cccg',
        ch: 30,
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["trat_term"],
        ementa: "Diagrama de fases Fe-C; caracterização microscópica dos ferros fundidos; normas técnicas para a especificação de ferros fundidos; classificação dos ferros fundidos: branco, cinzento, nodular e maleável. Ligas de Alumínio, Ligas de Titânio, Ligas de Magnésio e outras ligas.",
        objetivo: "Conhecer diferentes tipos de ferros fundidos e suas composições e conhecer os principais tipos de ligas leves e suas composições.",
      },
      {
        codigo: "AL2154",
        nome: "Tecnologia de Materiais Cerâmicos e Revestimentos",
        cat: 'em_cccg',
        ch: 30,
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["lab_met"],
        ementa: "Fundamentos das técnicas de obtenção de materiais cerâmicos. Definição, propriedades e caracterização de materiais cerâmicos. Tipos de matérias-primas. Processos de conformação. Tipos de secagem e sinterização. Tipos de revestimentos. Técnicas de aplicação dos revestimentos metálicos e cerâmicos. Principais aplicações.",
        objetivo: "Conhecer os principais materiais cerâmicos, os tipos de revestimento e suas características mecânicas e físicas.",
      },
      {
        codigo: "AL2043",
        nome: "Introdução à Robótica",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["alg_lin","calc2"],
        ementa: "Introdução à robótica, componentes dos robôs, transformação de coordenadas, transformação homogênea, cinemática direta de manipuladores, cinemática inversa de manipuladores, dinâmica de manipuladores, planejamento de trajetórias, robótica móvel, visão computacional, calibração de câmaras.",
        objetivo: "Compreender os princípios básicos da modelagem cinemática e dinâmica de robôs e estudar aplicações da geração de trajetória e visão computacional.",
      },
      {
        codigo: "AL0024",
        nome: "Circuitos Elétricos I",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["calc2"],
        ementa: "Conceitos fundamentais de circuitos concentrados. Análise de malhas e nós de circuitos elétricos. Dipolos elementares: resistores, capacitores, indutores e fontes. Associações série e paralelo. Circuitos lineares invariantes no tempo. Teoremas de redes. Circuitos de primeira ordem. Circuitos de segunda ordem.",
        objetivo: "Identificar, analisar e calcular circuitos lineares.",
      },
      {
        codigo: "AL2115",
        nome: "Projeto de Sistemas de Controle",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["ctrl_mec"],
        ementa: "Introdução ao projeto de sistemas de controle. Análise e projeto de sistemas de controle pela resposta em frequência (Controladores de Avanço, Atraso e Avanço-atraso de fase). Análise e projeto de sistemas de controle por PID (Proporcional, Integral e Derivativo) com métodos de sintonia de controladores PID. Análise e projeto de Sistemas de Controle pelo Espaço de Estados (Controlabilidade e Observabilidade).",
        objetivo: "Fornecer aos estudantes noções fundamentais e os instrumentos necessários para a análise e projeto de sistemas de controle que possam ser utilizados para modificar a dinâmica e o comportamento de sistemas mecânicos, para assim responder às suas especificações de projeto.",
      },
      {
        codigo: "AL0119",
        nome: "Custos de Produção",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["sist_prod","eq_dif1"],
        ementa: "Conceitos básicos em custos, classificação dos custos, apropriação dos custos diretos e indiretos, esquema básico da contabilidade de custos, produção contínua e por ordem de produção, noções sobre sistemas de apuração de custos, mapa de localização de custos - MLC, aplicação de custos indiretos de fabricação, produção conjunta, produção equivalente.",
        objetivo: "Abordar os principais conceitos e práticas envolvidas na Gestão de Custos das organizações.",
      },
      {
        codigo: "AL0036",
        nome: "Equações Diferenciais II",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["eq_dif1"],
        ementa: "Sequências e séries. Equações diferenciais lineares de coeficientes variáveis. Transformada de Laplace. Séries de Fourier. Equações diferenciais parciais.",
        objetivo: "Compreender soma infinita como extensão de soma finita e as noções de convergência e divergência. Resolver equações diferenciais ordinárias usando séries de potências e transformada de Laplace. Analisar os principais tipos de equações diferenciais parciais lineares de primeira e segunda ordem. Resolver equações diferenciais parciais de segunda ordem pelos métodos de separação de variáveis e de séries de Fourier.",
      },
      {
        codigo: "AL2062",
        nome: "Introdução à programação com Matlab",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["alg"],
        ementa: "Introdução ao MATLAB. O ambiente de programação MATLAB. Programação básica com MATLAB. Depuração com MATLAB. Estruturas de repetição. Funções definidas pelo usuário. Plotando e programando gráficos com MATLAB.",
        objetivo: "Este componente curricular objetiva descrever os conceitos básicos da programação com Matlab para o desenvolvimento de funções simples e complexas. É prevista a utilização de bibliotecas extras para auxiliar no desenvolvimento de algumas soluções a serem implementadas. Durante todo o componente curricular de forma a inserir tais conceitos e técnicas em um contexto prático, isto é, com exemplos marcantes e não apenas com palavras.",
      },
      {
        codigo: "AL2113",
        nome: "Linguagem Brasileira de Sinais - LIBRAS",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 15,
        ch_prat: 45,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Fundamentos linguísticos e culturais da Língua Brasileira de Sinais. Desenvolvimento de habilidades básicas expressivas e receptivas em Libras para promover comunicação entre seus usuários. Introdução aos Estudos Surdos.",
        objetivo: "Desenvolver as habilidades de recepção e de produção sinalizada, visando às competências linguística, discursiva e sociolinguística na Língua Brasileira de Sinais. Refletir sobre o conceito e a experiência visual dos surdos a partir de uma perspectiva sociocultural e linguística. Refletir sobre o papel da Língua de Sinais na vida dos surdos e nos espaços de interação entre surdos e ouvintes, particularmente nos ambientes educacionais.",
      },
      {
        codigo: "AL2148",
        nome: "Linguagem Brasileira de Sinais - LIBRAS II",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 15,
        ch_prat: 45,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["AL2113"],
        ementa: "Aprimoramento das estruturas da Libras e aperfeiçoamento da compreensão e produção em nível intermediário. Prática do uso da Libras em situações discursivas formais e informais (roleplay). Escrita de Sinais.",
        objetivo: "Aprofundar e articular a teoria com a prática, valorizando a pesquisa individual e coletiva da forma de comunicação e expressão dos surdos ou com deficiência auditiva, objetivando desse modo, que através do ensino da Língua Brasileira de Sinais (Libras) possam compreender a importância de assegurar a esses sujeitos o acesso à comunicação, à informação, motivar o desenvolvimento de tecnologias para pessoas surdas, pensando na sua efetiva integração na vida em sociedade. Aprofundar os conhecimentos no uso da Libras. Desenvolver a expressão visual espacial para facilitar a comunicação com a pessoa surda e identificar os principais aspectos linguísticos e gramaticais da Libras.",
      },
      {
        codigo: "AL2144",
        nome: "Relações Étnico Raciais",
        cat: 'em_cccg',
        ch: 30,
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Tratar os conceitos de etnia, raça, racialização, identidade, diversidade, diferença. Compreender os grupos étnicos “minoritários” e processos de colonização e pós-colonização. Políticas afirmativas para populações étnicas e políticas afirmativas específicas em educação. Populações étnicas e diásporas. Racismo, discriminação e perspectiva didático-pedagógica de educação antirracista. Currículo e política curriculares. História e cultura étnica na escola e itinerários pedagógicos. Etnia/Raça e a indissociabilidade de outras categorias da diferença. Cultura e hibridismo culturais. As etnociências na sala de aula. Movimentos Sociais e educação não formal. Pesquisas em educação no campo da educação e relações étnico-raciais.",
        objetivo: "Pensar o “outro”, o diferente, percebendo a complexidade de outras formações culturais e entendendo outras práticas culturais dentro de uma lógica própria, partindo de seus próprios parâmetros, construindo desta forma, uma percepção de que a nossa cultura é apenas uma das formas possíveis de perceber e interpretar o mundo e que todas as culturas são igualmente válidas e fazem sentido para seus participantes.",
      },
      {
        codigo: "AL2051",
        nome: "Tecnologia em Contexto Social",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Tecnologias para o desenvolvimento social. Direitos humanos. Cidadania. Formação continuada. Aspectos formais, informais e técnicos no desenvolvimento de tecnologias.",
        objetivo: "Perceber-se como cidadão, protagonista no cumprimento de direitos e deveres. Conhecer e propor tecnologias para o desenvolvimento social. Identificar diferentes atores envolvidos no desenvolvimento de tecnologia. Situar tecnologias em seu contexto social.",
      },
      {
        codigo: "AL2090",
        nome: "Português Instrumental",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Elaboração de textos dissertativo-argumentativos, considerando o emprego e a sistematização das normas técnicas utilizadas na pesquisa científica. Elaboração de Projeto de Pesquisa. Redação de Resumos Indicativo, Informativo e Resenha Crítica. Identificação de ideias principais e secundárias de um texto. Reconhecimento dos articuladores que estabelecem coesão no texto.",
        objetivo: "Apresentar ao acadêmico recursos linguísticos e textuais a fim de que ele seja capaz de redigir textos técnicos com clareza, harmonia, concisão e coerência.",
      },
      {
        codigo: "AL0486",
        nome: "Metodologia Científica",
        cat: 'em_cccg',
        ch: 30,
        ch_teo: 15,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Delineamento da pesquisa científica. Redação, apresentação e defesa do trabalho científico. Estrutura do trabalho científico.",
        objetivo: "Aprender a elaborar e apresentar trabalhos científicos, tais como projeto de pesquisa, artigos e trabalho de conclusão de curso.",
      },
      {
        codigo: "AL2240",
        nome: "LIBRAS I",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 0,
        ch_prat: 0,
        ch_ead_t: 15,
        ch_ead_p: 45,
        ch_ext: 0,
        prereqs: [],
        ementa: "Fundamentos linguísticos e culturais da Língua Brasileira de Sinais. Habilidades básicas expressivas e receptivas em Libras. Introdução aos Estudos Surdos.",
        objetivo: "Desenvolver as habilidades de recepção e de produção sinalizada, visando ao desenvolvimento da competência discursiva da Língua Brasileira de Sinais.",
      },
      {
        codigo: "AL2241",
        nome: "LIBRAS II",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 0,
        ch_prat: 0,
        ch_ead_t: 15,
        ch_ead_p: 45,
        ch_ext: 0,
        prereqs: [],
        ementa: "Aprimoramento das estruturas da Libras. Aperfeiçoamento da compreensão e produção em nível intermediário. Prática do uso da Libras em situações discursivas formais e informais (roleplay). Escrita de Sinais.",
        objetivo: "Aprofundar os conhecimentos relacionados à competência discursiva no uso da Libras, articulando teoria e prática, a fim de possibilitar a seus usuários a comunicação em Libras de forma contextualizada.",
      },
      {
        codigo: "AL2227",
        nome: "Laboratório de Engenharia de Software Aplicada em Negócios I",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 0,
        ch_prat: 0,
        ch_ead_t: 30,
        ch_ead_p: 30,
        ch_ext: 0,
        prereqs: [],
        ementa: "Introdução ao Aprendizado Baseado em Problemas (ABP). Introdução à atitude pró-inovação. Introdução sobre TRL, CRL e Produto Mínimo Viável (MVP). Estudo de campo das demandas do arranjo produtivo. Projeto ágil de software e ferramentas de prototipação. Introdução ao desenvolvimento de software orientado à hipótese e experimentação contínua.",
        objetivo: "Compreender e aplicar técnicas para o desenvolvimento do produto mínimo viável, concebido inicialmente como uma ideia de pesquisa.",
      },
      {
        codigo: "AL2232",
        nome: "Laboratório de Engenharia de Software Aplicada em Negócios II",
        cat: 'em_cccg',
        ch: 60,
        ch_teo: 0,
        ch_prat: 0,
        ch_ead_t: 30,
        ch_ead_p: 30,
        ch_ext: 0,
        prereqs: [],
        ementa: "Introdução a ecossistemas empreendedores. Características de startups e spin-offs de base tecnológica. Introdução à elaboração do plano de negócios. Empreendedorismo social. Concepção mercadológica do produto mínimo viável. Avaliação da Taxa Interna de Retorno (TIR). Estudo das parcerias e concorrentes. Prospecção de clientes e investidores. Incubação de empresas de base tecnológica.",
        objetivo: "Aplicar conhecimentos, técnicas, processos e ferramentas para a elaboração de ações empreendedoras derivadas das ações de ensino, pesquisa e extensão.",
      },
    ],
  };
})();
