/**
 * Engenharia de Software — PPC (UNIPAMPA Alegrete).
 * Códigos, CH, pré-requisitos e ementas alinhados ao ementário do PPC fornecido.
 */
(function () {
  const CCCG_EMENTA =
    'Componente Curricular Complementar de Graduação. Consulte a oferta semestral do curso.';

  window.GRADE_CURSO_CONFIG = {
    sigla: 'es',
    title: 'Grade Curricular — Engenharia de Software',
    subtitle: 'UNIPAMPA · Campus Alegrete · PPC 2020',
    maxSemesters: 9,
    disciplines: [
      {
        id: 'alg',
        name: 'Algoritmos e Programação',
        sem: 1,
        cat: 'es_computacao',
        prereqs: [],
        codigo: 'AL0323',
        ch: '120h',
        ch_teo: 45,
        ch_prat: 75,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Lógica de programação. Notações para algoritmos. Teste de mesa. Dados e expressões. Algoritmos sequenciais. Estruturas de controle. Variáveis compostas. Modularização: classes, objetos, atributos e métodos. Programação. Depuração. Arquivos de dados. Documentação de código.",
        objetivo: "Desenvolver programas de computadores, aplicando raciocínio lógico e conceitos de algoritmos e programação.",

      },
      {
        id: 'logica',
        name: 'Lógica Matemática',
        sem: 1,
        cat: 'es_matematica',
        prereqs: [],
        codigo: 'AL0324',
        ch: '60h',
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Introdução à lógica. Álgebra booleana. Lógica proposicional. Lógica de predicados.",
        objetivo: "Solucionar problemas utilizando raciocínio lógico baseado na lógica proposicional e de predicados.",

      },
      {
        id: 'matdisc',
        name: 'Matemática Discreta',
        sem: 1,
        cat: 'es_matematica',
        prereqs: [],
        codigo: 'AL0325',
        ch: '60h',
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Conjuntos. Álgebra de conjuntos. Relações. Funções parciais e totais. Relação de ordem e equivalência. Indução e recursão. Arranjo. Combinação. Permutação. Teoria da contagem.",
        objetivo: "Compreender conceitos e resolver problemas associados a conjuntos finitos com base na aritmética dos números naturais, aplicando os resultados na solução de problemas concretos. Aplicar conceitos de análise combinatória na modelagem e resolução de problemas.",

      },
      {
        id: 'prob1',
        name: 'Resolução de Problemas I',
        sem: 1,
        cat: 'es_software',
        prereqs: [],
        codigo: 'AL0326',
        ch: '120h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 90,
        ementa: "Requisitos de software. Identificação de requisitos. Especificação de requisitos. Análise de requisitos. Validação de requisitos. Controle de versão.",
        objetivo: "Executar processos de engenharia de requisitos para desenvolver requisitos de software dentro de um contexto, mantendo os artefatos gerados sob controle de versões.",

      },
      {
        id: 'bd',
        name: 'Banco de Dados',
        sem: 2,
        cat: 'es_computacao',
        prereqs: [],
        codigo: 'AL0327',
        ch: '60h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Fundamentos de bancos de dados. Sistema de gerenciamento de banco de dados. Modelo entidade-relacionamento. Modelo relacional. Transformações entre modelos. Normalização. Linguagens para definição e manipulação de Dados. Álgebra relacional. Transações.",
        objetivo: "Analisar, projetar e manipular modelos, esquemas e informações em bancos de dados, aplicando adequadamente os conceitos de banco de dados.",

      },
      {
        id: 'cs',
        name: 'Computação e Sociedade',
        sem: 2,
        cat: 'es_contexto_profissional',
        prereqs: [],
        codigo: 'AL0328',
        ch: '30h',
        ch_teo: 15,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 15,
        ementa: "História da computação. Cidadania. Impacto das tecnologias da computação na sociedade. Relações humanas. Ergonomia e saúde no ambiente de trabalho. Política e indústria de software. Universidade e seu entorno social.",
        objetivo: "Analisar as repercussões de tecnologias da computação, considerando aspectos humanos, sociais, culturais e políticos.",

      },
      {
        id: 'ihc',
        name: 'Interação Humano-Computador',
        sem: 2,
        cat: 'es_software',
        prereqs: [],
        codigo: 'AL0329',
        ch: '60h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Fundamentos e paradigmas de interação humano-computador. Aspectos cognitivos, ergonômicos e sociais. Qualidade em IHC. Avaliação de interfaces. Processos e técnicas de design em IHC. Tópicos especiais em IHC.",
        objetivo: "Avaliar e projetar sistemas computacionais interativos, considerando os usuários, os contextos de uso e a qualidade de interação e interface.",

      },
      {
        id: 'poo',
        name: 'Programação Orientada a Objetos',
        sem: 2,
        cat: 'es_computacao',
        prereqs: ['alg'],
        codigo: 'AL0330',
        ch: '90h',
        ch_teo: 30,
        ch_prat: 60,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Abstração. Associações. Encapsulamento. Herança. Polimorfismo. Linguagem de programação orientada a objetos. Tratamento de exceções. Interface gráfica com usuário.",
        objetivo: "Desenvolver software orientado a objetos, utilizando adequadamente recursos de linguagem de programação.",

      },
      {
        id: 'prob2',
        name: 'Resolução de Problemas II',
        sem: 2,
        cat: 'es_software',
        prereqs: ['alg'],
        codigo: 'AL0331',
        ch: '120h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 60,
        ch_ext: 0,
        ementa: "Técnicas e métodos de teste de software. Processo de teste de software. Automação de teste de software. Ferramentas de apoio e automação de teste de software. Geração de dados de teste.",
        objetivo: "Realizar teste de software de forma sistemática e apoiada por ferramentas de gerenciamento e automação.",

      },
      {
        id: 'aps',
        name: 'Análise e Projeto de Software',
        sem: 3,
        cat: 'es_software',
        prereqs: [],
        codigo: 'AL0332',
        ch: '60h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Fundamentos de análise e projeto. Linguagem de modelagem. Modelagem de software. Arquitetura de software. Análise e projeto Orientado a Objetos.",
        objetivo: "Elaborar os modelos necessários para projetar software tecnicamente viável e em conformidade com os requisitos.",

      },
      {
        id: 'arq',
        name: 'Arquitetura e Organização de Computadores',
        sem: 3,
        cat: 'es_computacao',
        prereqs: [],
        codigo: 'AL0333',
        ch: '30h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Organização de computadores. Arquitetura de computadores. Arquiteturas paralelas.",
        objetivo: "Compreender os princípios de arquitetura e organização de computadores e como esses princípios influenciam nos sistemas computacionais.",

      },
      {
        id: 'ed',
        name: 'Estruturas de Dados',
        sem: 3,
        cat: 'es_computacao',
        prereqs: ['alg'],
        codigo: 'AL0334',
        ch: '60h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Abstração de dados. Alternativas de implementação. Classificação, pesquisa e recursão. Arranjos. Listas. Pilhas. Filas. Mapas e dicionários. Árvores.",
        objetivo: "Selecionar e aplicar tipos abstratos de dados na solução de problemas reais.",

      },
      {
        id: 'inov',
        name: 'Inovação e Criatividade',
        sem: 3,
        cat: 'es_contexto_profissional',
        prereqs: [],
        codigo: 'AL0335',
        ch: '30h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Conceitos de inovação. Inovação em processos, produtos e serviços. Técnicas de inovação, de pensamento criativo e de identificação de novas oportunidades.",
        objetivo: "Compreender o conceito de inovação. Conhecer e saber aplicar técnicas de inovação e de pensamento criativo. Analisar casos de pensamento criativo e identificação de oportunidades que geram inovação.",

      },
      {
        id: 'lf',
        name: 'Linguagens Formais',
        sem: 3,
        cat: 'es_computacao',
        prereqs: [],
        codigo: 'AL0336',
        ch: '60h',
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Gramáticas. Linguagens regulares. Linguagens livres de contexto. Linguagens sensíveis ao contexto. Autômatos finitos determinísticos. Autômatos finitos não-determinísticos. Autômatos de pilha. Autômato linearmente limitado.",
        objetivo: "Compreender os conceitos formais de reconhecedores e geradores de linguagens.",

      },
      {
        id: 'prob3',
        name: 'Resolução de Problemas III',
        sem: 3,
        cat: 'es_software',
        prereqs: ['alg'],
        codigo: 'AL0337',
        ch: '120h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 60,
        ch_ext: 0,
        ementa: "Programação procedimental. Programação lógica. Programação funcional. Programação orientada a aspectos.",
        objetivo: "Resolver problemas através do desenvolvimento de software com diferentes paradigmas de programação.",

      },
      {
        id: 'apa',
        name: 'Análise e Projeto de Algoritmos',
        sem: 4,
        cat: 'es_computacao',
        prereqs: ['ed'],
        codigo: 'AL0338',
        ch: '60h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Análise de algoritmos. Análise de recorrência. Algoritmos gulosos. Divisão e conquista. Programação dinâmica. Conceitos e algoritmos para Grafos. Busca e ordenação.",
        objetivo: "Analisar e projetar algoritmos considerando a complexidade computacional envolvida, a fim de encontrar soluções computacionais ideais para os problemas.",

      },
      {
        id: 'probest',
        name: 'Probabilidade e Estatística',
        sem: 4,
        cat: 'es_matematica',
        prereqs: [],
        codigo: 'AL0022',
        ch: '60h',
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Estatística descritiva. Teoria das probabilidades. Distribuições de probabilidade. Teoria da amostragem. Estimação de parâmetros. Testes de hipóteses. Correlação e regressão.",
        objetivo: "Aplicar conceitos de probabilidade e estatística para analisar dados e interpretar resultados de pesquisa.",

      },
      {
        id: 'pqs',
        name: 'Processo e Qualidade de Software',
        sem: 4,
        cat: 'es_software',
        prereqs: [],
        codigo: 'AL0340',
        ch: '60h',
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Fundamentos de processo e qualidade. Modelos de processo. Abordagens tradicionais e ágeis. Qualidade de processo e de produto. Modelos de referência de qualidade. Modelagem de processo.",
        objetivo: "Sistematizar as práticas dos modelos de qualidade para viabilizar a melhoria contínua dos processos de desenvolvimento de software.",

      },
      {
        id: 'so',
        name: 'Sistemas Operacionais',
        sem: 4,
        cat: 'es_computacao',
        prereqs: [],
        codigo: 'AL0341',
        ch: '30h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Introdução aos sistemas operacionais. Gerenciamento de processos. Gerenciamento de memória. Gerenciamento de E/S. Sistemas de arquivos.",
        objetivo: "Analisar os aspectos fundamentais da estrutura e do funcionamento de sistemas operacionais.",

      },
      {
        id: 'vv',
        name: 'Verificação e Validação',
        sem: 4,
        cat: 'es_software',
        prereqs: [],
        codigo: 'AL0342',
        ch: '30h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Conceitos básicos de Verificação e Validação. Revisão, Inspeção, Walkthrough e Auditorias de Software. Técnicas de Leitura de Artefatos. Convenções de Codificação.",
        objetivo: "Fundamentar e aplicar os conceitos e técnicas que permitem identificar se um produto de software está sendo construído corretamente e se atende às expectativas das partes interessadas.",

      },
      {
        id: 'prob4',
        name: 'Resolução de Problemas IV',
        sem: 4,
        cat: 'es_software',
        prereqs: ['poo', 'aps'],
        codigo: 'AL0343',
        ch: '120h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 60,
        ch_ext: 0,
        ementa: "Fundamentos de padrões. Padrões de criação. Padrões estruturais. Padrões comportamentais. Outros padrões de projeto.",
        objetivo: "Reconhecer e aplicar os padrões de projeto orientados a objetos, bem como determinar sua aplicabilidade na solução de um determinado problema.",

      },
      {
        id: 'adm',
        name: 'Administração e Empreendedorismo',
        sem: 5,
        cat: 'es_contexto_profissional',
        prereqs: [],
        codigo: 'AL0104',
        ch: '60h',
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Definição de Administração. Funções do Administrador. Teorias da Administração. Funções empresariais. Gestão de estoques. Empreendedorismo.",
        objetivo: "Entender e compreender a natureza da gestão empresarial e os sistemas produtivos, aplicar as técnicas administrativas para a gestão e a tomada de decisão na produção de bens e serviços.",

      },
      {
        id: 'med',
        name: 'Medição e Análise',
        sem: 5,
        cat: 'es_software',
        prereqs: [],
        codigo: 'AL0345',
        ch: '30h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Fundamentos de medição. Medidas de software. Abordagem de medição e análise. Medidas funcionais.",
        objetivo: "Estabelecer estratégias de medição e análise para suportar a tomada de decisão no gerenciamento de software.",

      },
      {
        id: 'redes',
        name: 'Redes de Computadores',
        sem: 5,
        cat: 'es_computacao',
        prereqs: [],
        codigo: 'AL0344',
        ch: '30h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Fundamentos de redes. Estrutura e topologias de rede. Modelo TCP/IP com ênfase nas camadas de transporte e aplicação.",
        objetivo: "Compreender os conceitos essenciais de redes de computadores no desenvolvimento de software.",

      },
      {
        id: 'prob5',
        name: 'Resolução de Problemas V',
        sem: 5,
        cat: 'es_software',
        prereqs: ['prob1', 'poo', 'aps', 'prob2'],
        codigo: 'AL0346',
        ch: '120h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 90,
        ementa: "Fundamentos de evolução. Manutenção de software. Processo de evolução. Gerenciamento de evolução. Reengenharia de software. Refatoração.",
        objetivo: "Estabelecer abordagens de evolução de software para atender continuamente as demandas dos usuários.",

      },
      {
        id: 'cccg5',
        name: 'CCCGs',
        sem: 5,
        cat: 'es_cccg',
        prereqs: [],
        codigo: '—',
        ch: '120h',
        ementa: CCCG_EMENTA,
      },
      {
        id: 'mpa',
        name: 'Metodologia da Pesquisa Acadêmica',
        sem: 6,
        cat: 'es_software',
        prereqs: [],
        codigo: 'AL0339',
        ch: '60h',
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Ciência e conhecimento científico. Métodos científicos. Métodos de leitura. Análise e síntese de textos. Pesquisa bibliográfica sistemática. Trabalhos e publicações técnico-científicas. Fundamentos de engenharia de software experimental. Tipos de experimentos.",
        objetivo: "Conhecer, elaborar e realizar pesquisas acadêmicas sistemáticas em engenharia de software.",
        specialNote:
          'PPC: pré-requisito de integralização — anteprojeto de TCC aprovado (conforme coordenação).',
      },
      {
        id: 'prob6',
        name: 'Resolução de Problemas VI',
        sem: 6,
        cat: 'es_software',
        prereqs: ['prob1', 'poo', 'aps', 'prob2'],
        codigo: 'AL0347',
        ch: '120h',
        ch_teo: 15,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 105,
        ementa: "Fundamentos de projeto. Áreas de conhecimento. Processo de gerenciamento. Ferramentas de gerenciamento.",
        objetivo: "Empregar as técnicas de gerenciamento adequadas para o planejamento, controle e encerramento de projetos de software.",

      },
      {
        id: 'cccg6',
        name: 'CCCGs',
        sem: 6,
        cat: 'es_cccg',
        prereqs: [],
        codigo: '—',
        ch: '120h',
        ementa: CCCG_EMENTA,
      },
      {
        id: 'engeco',
        name: 'Engenharia Econômica',
        sem: 7,
        cat: 'es_contexto_profissional',
        prereqs: [],
        codigo: 'AL0125',
        ch: '30h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Matemática financeira. Engenharia econômica.",
        objetivo: "Desenvolver conhecimentos nos campos da matemática financeira e da engenharia econômica para possibilitar adequada tomada de decisão no campo análise de investimentos.",

      },
      {
        id: 'etica',
        name: 'Ética e Legislação em Computação',
        sem: 7,
        cat: 'es_contexto_profissional',
        prereqs: [],
        codigo: 'AL0348',
        ch: '30h',
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Responsabilidade ética na computação. Código de ética e prática profissional da ciência da computação e da engenharia de software. Legislação aplicada à computação.",
        objetivo: "Promover relações éticas e avaliar responsabilidades profissionais e sociais no exercício da Computação e da Engenharia de Software.",

      },
      {
        id: 'tcc1',
        name: 'Trabalho de Conclusão de Curso I',
        sem: 7,
        cat: 'es_software',
        prereqs: ['mpa'],
        codigo: 'AL0350',
        ch: '120h',
        ch_teo: 0,
        ch_prat: 120,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Elaboração do projeto de trabalho técnico-científico.",
        objetivo: "Planejar a síntese e a integração de conhecimentos adquiridos ao longo do curso.",

      },
      {
        id: 'cccg7',
        name: 'CCCGs',
        sem: 7,
        cat: 'es_cccg',
        prereqs: [],
        codigo: '—',
        ch: '120h',
        ementa: CCCG_EMENTA,
      },
      {
        id: 'tc',
        name: 'Teoria da Computação',
        sem: 8,
        cat: 'es_computacao',
        prereqs: ['matdisc'],
        codigo: 'AL0349',
        ch: '60h',
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Programas e máquinas. Máquinas universais. Funções recursivas. Computabilidade. Introdução à complexidade.",
        objetivo: "Compreender os fundamentos teóricos da Computação e entender a natureza dos problemas reais sob o ponto de vista da computabilidade.",

      },
      {
        id: 'tcc2',
        name: 'Trabalho de Conclusão de Curso II',
        sem: 8,
        cat: 'es_software',
        prereqs: ['tcc1'],
        codigo: 'AL0351',
        ch: '120h',
        ch_teo: 0,
        ch_prat: 120,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Elaboração do projeto de trabalho técnico-científico.",
        objetivo: "Sintetizar e integrar conhecimentos adquiridos ao longo do curso.",

      },
      {
        id: 'cccg8',
        name: 'CCCGs',
        sem: 8,
        cat: 'es_cccg',
        prereqs: [],
        codigo: '—',
        ch: '120h',
        ementa: CCCG_EMENTA,
      },
      {
        id: 'estagio',
        name: 'Estágio Obrigatório',
        sem: 9,
        cat: 'es_cccg',
        prereqs: [],
        codigo: 'AL0352',
        ch: '240h',
        ch_teo: 0,
        ch_prat: 240,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        ementa: "Atividades profissionais da área de Engenharia de Software.",
        objetivo: "Vivenciar o ambiente profissional e participar do processo de integração universidade-empresa.",
        specialMinCH: 1650,
      },
    ],
    /** Carga horária máxima de CCCG por semestre (PPC 2020). */
    cccgSemLimits: {
      5: 120,
      6: 120,
      7: 120,
      8: 120,
    },
    cccgs: [
    // Fundamentos da Matemática
    {codigo:'AL0009', nome:'Álgebra Linear',               cat:'es_matematica',  ch:60,  ch_teo:60,  ch_prat:0,   ch_ext:0, prereqs:[], ementa:'Matrizes. Determinantes. Sistemas lineares. Espaços vetoriais. Transformações lineares. Autovalores e autovetores.', objetivo:'Compreender os conceitos básicos relativos aos sistemas de equações lineares e espaços vetoriais.'},
    {codigo:'AL0001', nome:'Cálculo I',                    cat:'es_matematica',  ch:60,  ch_teo:60,  ch_prat:0,   ch_ext:0, prereqs:[], ementa:'Funções de uma variável. Limites. Continuidade. Derivadas. Regras de derivação. Máximos e mínimos e aplicações.', objetivo:'Compreender e aplicar as técnicas do cálculo diferencial para funções reais de uma variável real.'},
    {codigo:'AL0010', nome:'Cálculo II',                   cat:'es_matematica',  ch:60,  ch_teo:60,  ch_prat:0,   ch_ext:0, prereqs:[], ementa:'Integral indefinida e técnicas de integração. Integral definida. Funções de várias variáveis. Derivação parcial.', objetivo:'Dominar técnicas fundamentais do cálculo diferencial e integral para funções reais.'},
    {codigo:'AL0002', nome:'Geometria Analítica',          cat:'es_matematica',  ch:60,  ch_teo:60,  ch_prat:0,   ch_ext:0, prereqs:[], ementa:'Vetores no plano e no espaço. Retas e planos. Distância, área e volume. Cônicas e Quádricas.', objetivo:'Operar com vetores, distâncias, cônicas e quádricas, volumes e equações de retas e planos.'},

    // Fundamentos da Computação
    {codigo:'AL2040', nome:'Aprendizado de Máquina',                          cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Regressão linear e logística. Redes neurais. SVM. Árvores de decisão. Naïve Bayes. Agrupamento. K-médias. PCA. Sistemas de recomendação.', objetivo:'Introduzir o tópico de Aprendizado de Máquina, com ênfase em técnicas para classificação e reconhecimento de padrões.'},
    {codigo:'AL5129', nome:'Computação em Nuvem',                             cat:'es_computacao', ch:90,  ch_teo:60, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Conceitos de nuvem. Arquitetura de nuvem. Segurança na nuvem. Modelos de computação e armazenamento. Microserviços e computação sem servidor.', objetivo:'Compreender os aspectos gerais de ambientes de nuvem e serviços, segurança, arquitetura e definição de preço.'},
    {codigo:'AL0069', nome:'Inteligência Artificial',                         cat:'es_computacao', ch:60,  ch_teo:45, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Problemas, espaços e busca. Jogos. Representação de conhecimento e métodos de inferência. Abordagens alternativas de processamento de conhecimento.', objetivo:'Aprender as ideias básicas e as técnicas utilizadas no desenvolvimento de sistemas de computação inteligentes.'},
    {codigo:'AL2176', nome:'Introdução à Análise de Dados',                   cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Coleta, processamento, visualização e análise de dados para a tomada de decisões. Métodos e ferramentas para análise de dados.', objetivo:'Conhecer o processo de coleta e análise de dados aplicando métodos e ferramentas para responder a questões úteis à tomada de decisão.'},
    {codigo:'AL2047', nome:'Introdução ao Processamento de Imagens Digitais', cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Amostragem e quantização. Fundamentos do realce de imagens. Filtragem espacial. Morfologia matemática e segmentação de imagens.', objetivo:'Descrever os conceitos básicos dos principais tópicos relacionados ao processamento de imagens.'},
    {codigo:'AL2063', nome:'Introdução ao Processamento Paralelo',            cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Computadores paralelos. Programas paralelos para memória compartilhada e distribuída. Análise de desempenho.', objetivo:'Ensinar os conceitos básicos relacionados ao Processamento Paralelo e as técnicas e metodologias relativas a esta área.'},
    {codigo:'AL5006', nome:'Métodos de Otimização',                           cat:'es_computacao', ch:60,  ch_teo:60, ch_prat:0,  ch_ext:0, prereqs:[], ementa:'Programação linear e fluxo em redes. Programação não-linear. Programação inteira e combinatória. Métodos heurísticos.', objetivo:'Modelar e resolver problemas de otimização.'},
    {codigo:'AL2054', nome:'Processamento de Linguagem Natural',              cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Processamento de linguagem em Python. Corpus e recursos léxicos. Categorização de palavras. Classificação de textos. Extração de informação.', objetivo:'Compreender como analisar linguagens naturais usando técnicas e ferramentas em diversas áreas de aplicação.'},
    {codigo:'AL0070', nome:'Projeto de Linguagens de Programação',            cat:'es_computacao', ch:60,  ch_teo:45, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Critérios de avaliação de LPs. Nomes, vinculação e tipos. Estruturas de controle. Subprogramas e implementação.', objetivo:'Conhecer e familiarizar-se com as abstrações utilizadas na construção das linguagens de programação.'},
    {codigo:'AL2081', nome:'Projeto de Sistemas Digitais',                    cat:'es_computacao', ch:60,  ch_teo:15, ch_prat:45, ch_ext:0, prereqs:[], ementa:'Introdução ao projeto e implementação de sistemas digitais. Linguagens de descrição. Ambientes de simulação. Plataformas de prototipação.', objetivo:'Auxiliar o aluno a desenvolver sistemas digitais e compreender o fluxo completo para concepção e prototipação.'},
    {codigo:'AL5086', nome:'Segurança de Sistemas',                           cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Primitivas Criptográficas. Criptografia Simétrica e de Chave Pública. Assinatura Digital. Protocolos de Autenticação. Tecnologias de Segurança.', objetivo:'Compreender e aplicar os conhecimentos essenciais de segurança de sistemas e da informação.'},
    {codigo:'AL2185', nome:'Tópicos em Ataque e Defesa de Sistemas',          cat:'es_computacao', ch:30,  ch_teo:15, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Técnicas que precedem um ataque. Metodologias e ferramentas para realização de ataques. Técnicas de mitigação.', objetivo:'Compreender na teoria e aplicar na prática conhecimentos relativos a ataques e defesa de sistemas.'},
    {codigo:'AL2191', nome:'Tópicos em Blockchain e Smart Contracts',         cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Esquemas de criação de blocos em uma Blockchain. Protocolos de consenso. Projeto e implementação de Smart Contracts. Criptomoedas.', objetivo:'Compreender os aspectos teóricos e práticos relacionados à concepção, projeto e implementação de tecnologias de Blockchain.'},
    {codigo:'AL2111', nome:'Tópicos de Redes de Computadores',                cat:'es_computacao', ch:30,  ch_teo:15, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Redes sem fio e móveis. Gerenciamento. Redes orientadas a conteúdo. Internet das coisas. Avaliação de desempenho.', objetivo:'Apresentar tópicos atuais na área de redes de computadores.'},
    {codigo:'AL2178', nome:'Tópicos em Resolução de Problemas em Sistemas Unix/Linux I',  cat:'es_computacao', ch:30, ch_teo:15, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Introdução a sistemas Unix/Linux. Shell scripting. Automação de tarefas e resolução de problemas.', objetivo:'Compreender os aspectos teóricos e práticos relacionados ao gerenciamento de sistemas Unix/Linux.'},
    {codigo:'AL2184', nome:'Tópicos em Resolução de Problemas em Sistemas Unix/Linux II', cat:'es_computacao', ch:30, ch_teo:15, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Programação avançada com shell scripting e outras linguagens. Gerenciamento e segurança de servidores. Automação de backup.', objetivo:'Compreender e aplicar os aspectos intermediários e avançados relacionados ao gerenciamento e programação de sistemas Unix/Linux.'},
    {codigo:'AL2177', nome:'Tópicos de Segurança de Sistemas e da Informação', cat:'es_computacao', ch:60, ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Primitivas Criptográficas. Criptografia Simétrica e de Chave Pública. Assinatura Digital. Protocolos de Autenticação.', objetivo:'Compreender e aplicar os conhecimentos essenciais de segurança de sistemas e da informação.'},
    {codigo:'AL2048', nome:'Desafios de Programação',                         cat:'es_computacao', ch:60,  ch_teo:0,  ch_prat:60, ch_ext:0, prereqs:[], ementa:'Desafios e competições de programação. Estruturas de dados. Ordenação. Teoria dos números. Grafos. Geometria computacional.', objetivo:'Analisar problemas e projetar soluções eficientes para desafios de programação e competições.'},
    {codigo:'AL2246', nome:'Tópicos em Ataques e Defesa de Sistemas (EAD)',   cat:'es_computacao', ch:30,  ch_teo:0,  ch_prat:0,  ch_ext:0, prereqs:[], ementa:'Técnicas que precedem um ataque. Metodologias e ferramentas para realização de ataques. Técnicas de mitigação.', objetivo:'Compreender na teoria e aplicar na prática conhecimentos relativos a ataques e defesa de sistemas.'},
    {codigo:'AL2247', nome:'Introdução ao Processamento de Imagens Digitais (EAD)', cat:'es_computacao', ch:60, ch_teo:0, ch_prat:0, ch_ext:0, prereqs:[], ementa:'Amostragem e quantização. Fundamentos do realce de imagens. Filtragem espacial. Morfologia matemática e segmentação.', objetivo:'Compreender os conceitos e definições de imagem digital e realizar manipulação básica de imagens digitais.'},
    {codigo:'AL5088', nome:'Programabilidade de Infraestruturas de Redes',    cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Redes definidas por software. Funções virtualizadas de rede. Programabilidade do plano de controle e de dados.', objetivo:'Permitir que o aluno desenvolva habilidades técnicas para contribuir com tecnologias emergentes em redes.'},
    {codigo:'AL5149', nome:'Tópicos Especiais em Análise de Imagens',         cat:'es_computacao', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Segmentação de Imagens com Redes Profundas. Aprendizado de Representações. Reconhecimento de Padrões Visuais com Deep Learning.', objetivo:'Compreender os fundamentos de processamento e análise de imagens e dominar técnicas envolvidas no desenvolvimento de sistemas baseados em imagens.'},

    // Engenharia de Software
    {codigo:'AL2095', nome:'Acessibilidade Web',                              cat:'es_software', ch:30,  ch_teo:15, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Introdução à acessibilidade Web. Web standards. Recomendações de acessibilidade Web. Ferramentas e estratégias de avaliação.', objetivo:'Conhecer web standards e analisar princípios e recomendações para o desenvolvimento de sistemas web acessíveis.'},
    {codigo:'AL2164', nome:'Automação de Teste de Sistema',                   cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Introdução ao teste automatizado de sistema. Técnicas de automação. Ferramentas de apoio. Geração automática de dados de teste.', objetivo:'Aplicar os conceitos, técnicas e ferramentas para prover suporte à automação da etapa de teste de sistema.'},
    {codigo:'AL2187', nome:'Desenvolvimento de Qualquer Coisa como um Serviço', cat:'es_software', ch:60, ch_teo:30, ch_prat:30, ch_ext:0, prereqs:['poo'], ementa:'Introdução à programação de sistemas para XaaS. IaaS, PaaS e SaaS. Fundamentos de desenvolvimento de software para computação em nuvem.', objetivo:'Aplicar conceitos, técnicas e ferramentas para desenvolvimento da camada de serviços de aplicações (XaaS).'},
    {codigo:'AL2058', nome:'Desenvolvimento de Software para Dispositivos Móveis', cat:'es_software', ch:60, ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Computação móvel, pervasiva e ubíqua. Tipos de dispositivos móveis. Desenvolvimento de aplicações para Android.', objetivo:'Aprender os conceitos básicos relacionados ao desenvolvimento de software para dispositivos móveis.'},
    {codigo:'AL2119', nome:'Desenvolvimento de Software para Web Semântica',  cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Fundamentos de web semântica. Modelagem de ontologias. Desenvolvimento de aplicações.', objetivo:'Prover visão prática e teórica sobre o desenvolvimento de aplicações Web baseadas nos conceitos de Web semântica.'},
    {codigo:'AL2175', nome:'Engenharia Dirigida por Modelos',                 cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Introdução à MDE. Implementação de fábricas de software. Criação de linguagens específicas de domínio (DSLs). Engenharia de round-trip.', objetivo:'Aplicar conceitos, técnicas e ferramentas para prover suporte à Engenharia Dirigida por Modelos (MDE).'},
    {codigo:'AL2174', nome:'Engenharia de Software Orientada a Agentes',      cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Conceitos de Agentes e Sistemas Multi-agentes. Agent Oriented Software Engineering (AOSE). Linguagens de modelagem e metodologias AOSE.', objetivo:'Aprender os conceitos de linguagens de modelagem para sistemas multiagentes e as principais metodologias para o desenvolvimento desse tipo de sistema.'},
    {codigo:'AL2227', nome:'Laboratório de Engenharia de Software Aplicada em Negócios I (EAD)', cat:'es_software', ch:60, ch_teo:0, ch_prat:0, ch_ext:0, prereqs:[], ementa:'Aprendizado Baseado em Problemas. Atitude pró-inovação. TRL e MVP. Projeto ágil de software. Desenvolvimento orientado à hipótese e experimentação.', objetivo:'Compreender e aplicar técnicas para o desenvolvimento do produto mínimo viável.'},
    {codigo:'AL2232', nome:'Laboratório de Engenharia de Software Aplicada em Negócios II (EAD)', cat:'es_software', ch:60, ch_teo:0, ch_prat:0, ch_ext:0, prereqs:[], ementa:'Ecossistemas empreendedores. Startups e spin-offs. Plano de negócios. Empreendedorismo social. MVP. Taxa Interna de Retorno.', objetivo:'Aplicar conhecimentos, técnicas, processos e ferramentas para a elaboração de ações empreendedoras.'},
    {codigo:'AL0303', nome:'Laboratório de Desenvolvimento de Jogos Digitais', cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Conceitos básicos de jogos digitais. Interface gráfica. Animação e sonorização. Detecção de colisão. IA e física em jogos. Frameworks e engines.', objetivo:'Desenvolver habilidades de projeto e programação no contexto de jogos digitais.'},
    {codigo:'AL2188', nome:'Linguagens Específicas de Domínio',               cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:['poo'], ementa:'Introdução às DSLs. Engenharia de Domínio. Projeto Dirigido pelo Domínio (DDD). Critérios de qualidade em DSLs.', objetivo:'Aplicar conceitos, técnicas, métodos e ferramentas de suporte para a criação de Linguagens Específicas de Domínio (DSL).'},
    {codigo:'AL2204', nome:'Práticas de Interação Humano-Computador no Desenvolvimento de Software', cat:'es_software', ch:60, ch_teo:15, ch_prat:45, ch_ext:0, prereqs:[], ementa:'Wicked Problems. IHC no processo de desenvolvimento de software. Métodos e ferramentas para integração de IHC no desenvolvimento.', objetivo:'Compreender técnicas, estratégias e métodos que apoiem a integração da IHC nas etapas do processo de desenvolvimento de software.'},
    {codigo:'AL2077', nome:'Práticas em Programação',                         cat:'es_software', ch:60,  ch_teo:15, ch_prat:45, ch_ext:0, prereqs:[], ementa:'Prática de programação. Criação e manipulação de funções e bibliotecas. Alocação de memória. Uso de estruturas de dados. Arquivos.', objetivo:'Permitir que o aluno desenvolva o raciocínio lógico aplicado à solução de problemas em nível computacional.'},
    {codigo:'AL0214', nome:'Programação para Web',                            cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Introdução a padrões Web. Programação no lado do cliente. Programação no lado do servidor. HTML, CSS, JavaScript, PHP.', objetivo:'Proporcionar conhecimentos teórico-práticos em programação e tecnologias para desenvolvimento web.'},
    {codigo:'AL0133', nome:'Sistemas de Informação',                          cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Introdução a sistemas de informação. Aplicações de sistemas de informação. Questões gerenciais, organizacionais, técnicas, éticas e sociais.', objetivo:'Conhecer diferentes aplicações para sistemas de informação e desenvolver visão holística e estratégica das TICs.'},
    {codigo:'AL2168', nome:'Teste de Desempenho',                             cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Técnicas de automação do teste de desempenho. Processo do teste de desempenho. Ferramentas de apoio. Métricas de desempenho.', objetivo:'Aplicar os conceitos, técnicas e ferramentas para prover suporte ao teste de desempenho.'},
    {codigo:'AL2244', nome:'Engenharia de Software Seguro',                   cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Elicitação de requisitos de segurança. Design seguro. Implementação segura. Autenticação e controle de acesso. Testes de penetração. Mitigação de ameaças.', objetivo:'Compreender e aplicar os princípios e práticas de desenvolvimento de software seguro.'},
    {codigo:'AL2248', nome:'Engenharia de Software Seguro (EAD)',             cat:'es_software', ch:60,  ch_teo:0,  ch_prat:0,  ch_ext:0, prereqs:[], ementa:'Elicitação de requisitos de segurança. Design seguro. Implementação segura. Autenticação e controle de acesso. Testes de penetração. Mitigação de ameaças.', objetivo:'Compreender e aplicar os princípios e práticas de desenvolvimento de software seguro.'},
    {codigo:'AL5126', nome:'Tópicos em Engenharia de Requisitos',             cat:'es_software', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Fundamentos de engenharia de requisitos. Elicitação, análise, especificação e validação. Requisitos Ágeis. Rastreabilidade.', objetivo:'Conhecer técnicas atuais de elicitação, análise, especificação e validação de requisitos.'},

    // Contexto Profissional
    {codigo:'AL2036', nome:'Acessibilidade e Inclusão Digital',               cat:'es_contexto_profissional', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Acessibilidade e design universal. Legislação de acessibilidade. Recursos de tecnologia assistiva. Informática acessível.', objetivo:'Compreender acessibilidade e sua inter-relação com o processo de inclusão digital na perspectiva do Design Universal.'},
    {codigo:'AL2098', nome:'Computação e Cidadania',                          cat:'es_contexto_profissional', ch:30,  ch_teo:15, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Acesso participativo e universal ao conhecimento. Participação democrática mediada por computador. Ética em computação. Design Participativo.', objetivo:'Conhecer os desafios da computação no Brasil e analisar o papel social da computação.'},
    {codigo:'AL2113', nome:'Libras',                                          cat:'es_contexto_profissional', ch:60,  ch_teo:15, ch_prat:45, ch_ext:0, prereqs:[], ementa:'Fundamentos linguísticos e culturais da Língua Brasileira de Sinais. Habilidades básicas expressivas e receptivas em Libras. Introdução aos Estudos Surdos.', objetivo:'Desenvolver as habilidades de recepção e de produção sinalizada na Língua Brasileira de Sinais.'},
    {codigo:'AL2148', nome:'Libras 2',                                        cat:'es_contexto_profissional', ch:60,  ch_teo:15, ch_prat:45, ch_ext:0, prereqs:[], ementa:'Aprimoramento das estruturas da Libras em nível intermediário. Prática em situações discursivas formais e informais. Escrita de Sinais.', objetivo:'Especializar alunos mediante o aprofundamento e articulação da teoria com a prática da comunicação em Libras.'},
    {codigo:'AL2109', nome:'Modelo de Negócio na Área de Software',           cat:'es_contexto_profissional', ch:30,  ch_teo:30, ch_prat:0,  ch_ext:0, prereqs:[], ementa:'Modelos de negócio. Startups. Agregação de valor em produtos e serviços de software.', objetivo:'Compreender o conceito de startup, agregação de valor e modelos de negócios na área de software.'},
    {codigo:'AL2080', nome:'Produção de Textos Científicos e Latex',          cat:'es_contexto_profissional', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Princípios da escrita eficaz. Construção de frases e parágrafos. O formato de um manuscrito original. O processo de publicação. Uso do LaTeX.', objetivo:'Capacitar o aluno a expressar-se adequadamente em textos científicos e introduzir as facilidades do LaTeX.'},
    {codigo:'AL2013', nome:'Redação Técnica',                                 cat:'es_contexto_profissional', ch:45,  ch_teo:30, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Redação de parágrafos de resumo e artigos acadêmicos. Estrutura lógica de textos técnicos. Elementos linguísticos de progressão textual.', objetivo:'Apresentar ao acadêmico recursos linguísticos e textuais para redigir textos técnicos com clareza e coerência.'},
    {codigo:'AL2144', nome:'Relações Étnico-raciais',                         cat:'es_contexto_profissional', ch:30,  ch_teo:30, ch_prat:0,  ch_ext:0, prereqs:[], ementa:'Conceitos de etnia, raça, racialização, identidade e diversidade. Políticas afirmativas. Racismo e educação antirracista.', objetivo:'Mudar o ponto de referência do aluno para pensar o outro, percebendo a complexidade de outras formações culturais.'},
    {codigo:'AL2051', nome:'Tecnologia em Contexto Social',                   cat:'es_contexto_profissional', ch:60,  ch_teo:30, ch_prat:30, ch_ext:0, prereqs:[], ementa:'Tecnologias para o desenvolvimento social. Direitos humanos. Cidadania. Aspectos formais, informais e técnicos no desenvolvimento de tecnologias.', objetivo:'Perceber-se como cidadão e conhecer tecnologias para o desenvolvimento social.'},
    {codigo:'AL2240', nome:'Libras I (EaD)',                                  cat:'es_contexto_profissional', ch:60,  ch_teo:0,  ch_prat:0,  ch_ext:0, prereqs:[], ementa:'Fundamentos linguísticos e culturais da Língua Brasileira de Sinais. Habilidades básicas expressivas e receptivas em Libras.', objetivo:'Desenvolver as habilidades de recepção e de produção sinalizada na Língua Brasileira de Sinais.'},
    {codigo:'AL2241', nome:'Libras II (EaD)',                                 cat:'es_contexto_profissional', ch:60,  ch_teo:0,  ch_prat:0,  ch_ext:0, prereqs:['AL2240'], ementa:'Aprimoramento das estruturas da Libras em nível intermediário. Escrita de Sinais.', objetivo:'Aprofundar os conhecimentos relacionados à competência discursiva no uso da Libras.'},
    {codigo:'AL0160', nome:'Segurança no Trabalho e Gestão Ambiental',       cat:'es_contexto_profissional', ch:45,  ch_teo:30, ch_prat:15, ch_ext:0, prereqs:[], ementa:'Introdução à segurança do trabalho. Legislação e normatização. Higiene e medicina do trabalho. EPI/EPC. Ergonomia. Ecologia e meio ambiente.', objetivo:'Estudar as normas vigentes relativas à segurança, higiene e medicina do trabalho e à gestão ambiental.'},
    {codigo:'AL5151', nome:'Produção de Textos Científicos (EaD)',            cat:'es_contexto_profissional', ch:60,  ch_teo:0,  ch_prat:0,  ch_ext:0, prereqs:[], ementa:'Princípios da escrita eficaz. Formatos de textos científicos. Revisões e comentários. Processos de submissão e publicação.', objetivo:'Capacitar o aluno a expressar-se adequadamente em textos científicos e facilitar a elaboração de documentos científicos.'},
  ],
  };
})();
