/**
 * Dados da grade: ET (UNIPAMPA Alegrete).
 * Ementas e objetivos separados, CH alinhada ao ementário oficial (PPC).
 * Semestragem e pré-requisitos conforme matriz curricular.
 */
(function () {
  'use strict';
  const CCCG_EMENTA =
    'Componente Curricular Complementar de Graduação. Consulte a oferta semestral do curso.';

  const disciplines = [
    {
      id: 'calc1',
      name: 'Cálculo I',
      sem: 1,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0363',
      ch: '90h',
      ch_teo: 90,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Revisão de matemática básica. Noções básicas de conjuntos. A reta real. Intervalos e desigualdades. Funções de uma variável. Limites. Continuidade. Derivadas. Regras de derivação. Regra da cadeia. Derivação implícita. Diferencial. Regra de L’Hôpital, máximos e mínimos e outras aplicações.",
      objetivo: "Compreender e aplicar as técnicas do Cálculo Diferencial para funções reais de uma variável real, dando ênfase às suas aplicações.",
    },
    {
      id: 'geom',
      name: 'Geometria Analítica',
      sem: 1,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0002',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Vetores no plano e no espaço. Retas no plano e no espaço. Estudo do plano. Distância, área e volume. Cônicas. Quádricas.",
      objetivo: "Desenvolver noções e conhecimento sobre vetores, curvas, e superfícies no plano e no espaço.",
    },
    {
      id: 'fis1',
      name: 'Física I',
      sem: 1,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0003',
      ch: '75h',
      ch_teo: 60,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Movimento retilíneo. Movimento no plano. Leis de Newton. Trabalho e energia cinética. Energia potencial e conservação de energia. Quantidade de movimento linear e choque. Rotação de corpos rígidos. Gravitação.",
      objetivo: "Identificar fenômenos naturais em termos de quantidade e regularidade, bem como interpretar princípios fundamentais que generalizam as relações entre eles e aplicá-los na resolução de problemas simples da mecânica clássica.",
    },
    {
      id: 'intro_ct',
      name: 'Introdução à Ciência e Tecnologia',
      sem: 1,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0004',
      ch: '30h',
      ch_teo: 30,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "A evolução tecnológica ao longo dos tempos. Disseminação da cultura científica e tecnológica. Metodologia científica. Mercado de trabalho na área tecnológica. Comunicação e Expressão. Entidades científicas e profissionais.",
      objetivo: "Apresentar um panorama geral sobre os cursos da área da tecnologia, as áreas de atuação, carreira profissional e oportunidades de desenvolvimento.",
    },
    {
      id: 'alg',
      name: 'Algoritmos e Programação',
      sem: 1,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0005',
      ch: '60h',
      ch_teo: 30,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Noções de lógica de programação. Dados, expressões e algoritmos sequenciais. Estruturas de controle. Estruturas complexas. Modularização.",
      objetivo: "Desenvolver o raciocínio lógico aplicado à solução de problemas em nível computacional, além de introduzir os conceitos básicos de desenvolvimento de algoritmos, de forma a propiciar uma visão crítica e sistemática sobre resolução de problemas e prepará-lo para a atividade de programação.",
    },
    {
      id: 'seg_trab',
      name: 'Segurança e Saúde no Trabalho',
      sem: 1,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0368',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução à segurança no trabalho. Legislação e normatização. EPI/EPC. Higiene e medicina do trabalho. Ergonomia. Segurança com a eletricidade. Proteção contra incêndios. Primeiros socorros.",
      objetivo: "Estudar as normas vigentes relativas à segurança, saúde, higiene e medicina no trabalho.",
    },
    {
      id: 'ext1',
      name: 'Extensão I',
      sem: 1,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0411',
      ch: '45h',
      ch_teo: 15,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 30,
      ementa: "Introdução à extensão universitária e sua curricularização no curso de Engenharia de Telecomunicações. Normas de extensão universitária do curso. Estrutura organizacional da extensão na instituição. Introdução aos programas institucionais extensionistas. Prospecção de atividades de extensão nas áreas de tecnologia. As áreas temáticas de atuação no curso são: Eletromagnetismo Aplicado, Sinais e Sistemas, Eletrônica ou Computação.",
      objetivo: "Introduzir o discente na extensão universitária, mostrando como seu conhecimento acadêmico pode contribuir significativamente para a comunidade.",
    },
    {
      id: 'alg_lin',
      name: 'Álgebra Linear',
      sem: 2,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0009',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Matrizes. Determinantes. Sistemas lineares. Espaços Vetoriais. Espaços com produto interno. Transformações Lineares. Autovalores e autovetores. Diagonalização de operadores.",
      objetivo: "Compreender os conceitos básicos relativos aos sistemas de equações lineares, suas operações e propriedades existentes. Desenvolver o raciocínio matemático, abstração e visualização de vetores, espaços vetoriais e suas operações no plano e no espaço. Operar com sistemas de equações lineares, espaços vetoriais, produtos, transformações lineares, autovalores e espaços com produto interno.",
    },
    {
      id: 'calc2',
      name: 'Cálculo II',
      sem: 2,
      cat: 'et_basico',
      prereqs: ["calc1"],
      codigo: 'AL0010',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Integral indefinida e técnicas de integração. Integral definida. O teorema fundamental do cálculo. Integral imprópria. Aplicações do cálculo integral: cálculo de áreas, cálculo de volumes por rotação e invólucro cilíndrico, comprimento de arco, sistema de coordenadas polares e área de uma região em coordenadas polares. Funções de várias variáveis reais. Derivação parcial. Gradiente e derivadas direcionais.",
      objetivo: "Dominar técnicas fundamentais do cálculo diferencial e integral para funções reais de uma variável real, possibilitando a capacitação para a resolução de problemas aplicados em diversos campos da ciência e da engenharia. Compreender os conceitos de limite e diferenciabilidade para funções de várias variáveis, viabilizando um melhor entendimento das suas aplicações.",
    },
    {
      id: 'fis2',
      name: 'Física II',
      sem: 2,
      cat: 'et_basico',
      prereqs: ["fis1"],
      codigo: 'AL0011',
      ch: '75h',
      ch_teo: 60,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Oscilações. Ondas. Temperatura. Primeira e Segunda Lei da Termodinâmica. Teoria cinética dos gases. Hidrostática. Hidrodinâmica.",
      objetivo: "Distinguir entre os fenômenos físicos de oscilações e ondas. Compreender a diferença entre calor e temperatura. Aplicar e manipular equações para resolução de problemas. Relacionar os princípios físicos estudados às aplicações práticas da engenharia.",
    },
    {
      id: 'quim',
      name: 'Química Geral e Experimental',
      sem: 2,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0366',
      ch: '45h',
      ch_teo: 30,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Atomística. Ligações químicas. Quantidade de matéria. Fórmulas químicas.Equações químicas. Estequiometria das reações. Reações químicas. Parte experimental.",
      objetivo: "Conhecer e aplicar conceitos básicos de Química Geral teórica e experimental.",
    },
    {
      id: 'circ_dig',
      name: 'Circuitos Digitais',
      sem: 2,
      cat: 'et_computacao',
      prereqs: [],
      codigo: 'AL0013',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Portas lógicas. Simplificação de funções booleanas. Hardware digital. Componentes Lógicos. Elementos de memória. Circuitos lógicos sequenciais.",
      objetivo: "Analisar, simplificar e sintetizar sistemas à base de circuitos digitais.",
    },
    {
      id: 'probest',
      name: 'Probabilidade e Estatística',
      sem: 2,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0022',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Estatística descritiva. Teoria das probabilidades. Distribuições discretas de probabilidades. Distribuições contínuas de probabilidades. Teoria da amostragem. Estimação de parâmetros. Testes de Hipótese. Correlação e regressão.",
      objetivo: "Ter um sólido conhecimento sobre cálculo de probabilidade, variáveis aleatórias, processos aleatórios e estatística.",
    },
    {
      id: 'circ_med',
      name: 'Introdução a Circuitos e Medidas Elétricas',
      sem: 2,
      cat: 'et_eletronica',
      prereqs: [],
      codigo: 'AL0412',
      ch: '30h',
      ch_teo: 0,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução a componentes passivos. Introdução de materiais elétricos e dielétricos. Elementos de circuitos elétricos, introdução à análise de circuitos elétricos em corrente contínua e Leis de Kirchhoff. Introdução à simulação de circuitos elétricos. Erro de medidas elétricas. Critérios de segurança no laboratório e segurança em trabalhos com eletricidade. Equipamentos básicos de eletricidade: matriz de contatos, voltímetro, amperímetro, wattímetro, osciloscópio, gerador de sinais.",
      objetivo: "Compreender e aplicar os conceitos de análise, simulação e montagem experimental de circuitos elétricos básicos em regime permanente.",
    },
    {
      id: 'eq_dif1',
      name: 'Equações Diferenciais I',
      sem: 3,
      cat: 'et_basico',
      prereqs: ["calc2"],
      codigo: 'AL0019',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Conceito e classificação de Equações diferenciais. Tipos de soluções. Equações diferenciais de primeira ordem. Equações diferenciais de segunda ordem. Equações lineares de ordem superior. Sistemas lineares de equações diferenciais.",
      objetivo: "Desenvolver conceitos matemáticos relacionados às equações diferenciais. Aplicar os conceitos da componente curricular em problemas de engenharia. Compreender/interpretar os resultados obtidos. Adotar a técnica de resolução de equação diferencial que melhor se adapta ao problema proposto.",
    },
    {
      id: 'calc3',
      name: 'Cálculo III',
      sem: 3,
      cat: 'et_basico',
      prereqs: ["calc2"],
      codigo: 'AL0020',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Integrais duplas (coordenadas polares) e triplas (sistemas de coordenadas cartesianas, cilíndricas e esféricas). Funções vetoriais. Campos vetoriais. Integrais curvilíneas. Operadores divergente e rotacional. Teorema de Green. Integrais de superfície. Teoremas de Gauss e Stokes.",
      objetivo: "Compreender os conceitos de integração para funções de várias variáveis, bem como suas aplicações. Compreender e aplicar os conceitos de derivada e integral de funções vetoriais e aplicar os teoremas da divergência e Stokes em alguns casos particulares.",
    },
    {
      id: 'fis3',
      name: 'Física III',
      sem: 3,
      cat: 'et_basico',
      prereqs: ["calc2"],
      codigo: 'AL0021',
      ch: '75h',
      ch_teo: 60,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Lei de Coulomb. Campo elétrico. Potencial eletrostático. Capacitância e capacitores. Dielétricos. Corrente elétrica. Campo magnético. Lei de Ampère. Lei de indução. Indutância e indutores.",
      objetivo: "Conhecer e interpretar os fenômenos físicos relacionados a eletricidade e magnetismo a partir da teoria eletromagnética.",
    },
    {
      id: 'gest_amb',
      name: 'Fundamentos da Gestão Ambiental',
      sem: 3,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0390',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Ambiente e desenvolvimento sustentável. Políticas Ambientais. Projetos ambientais.",
      objetivo: "Conhecer as principais definições, legislações e projetos ambientais requeridos, pertinentes aos projetos de engenharia que possam apresentar impactos ambientais.",
    },
    {
      id: 'arq_comp',
      name: 'Arquitetura e Organização de Computadores I',
      sem: 3,
      cat: 'et_computacao',
      prereqs: ["circ_dig"],
      codigo: 'AL0023',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Componentes de computadores. Medidas de desempenho. Organização da memória. Arquitetura do conjunto de instruções. Modos de endereçamento. Linguagem de montagem. Implementação do caminho de dados de processadores. Parte operacional. Parte de controle. Aritmética computacional.",
      objetivo: "Descrever os elementos constituintes de um sistema computacional, analisar o fluxo elementar de seus módulos e desenvolver uma visão crítica sobre os requisitos de desempenho associados ao sistema computacional.",
    },
    {
      id: 'circ1',
      name: 'Circuitos Elétricos I',
      sem: 3,
      cat: 'et_eletronica',
      prereqs: ["calc2"],
      codigo: 'AL0413',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Conceitos fundamentais de circuitos concentrados. Análise de malhas e nós de circuitos elétricos. Dipolos elementares: resistores, capacitores, indutores e fontes. Associações série e paralelo. Circuitos lineares invariantes no tempo. Teoremas de redes. Circuitos de primeira ordem. Circuitos de segunda ordem. Simulação de circuitos de primeira e de segunda ordem.",
      objetivo: "Identificar, analisar e calcular circuitos lineares.",
    },
    {
      id: 'dtcd',
      name: 'Desenho Técnico Civil e Digital',
      sem: 3,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0367',
      ch: '60h',
      ch_teo: 30,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Desenho arquitetônico, desenho de estruturas, desenho de instalações hidrossanitárias, desenho de instalações elétricas. Desenho universal. Desenho digital. Renderização.",
      objetivo: "Desenvolver desenhos com a correta utilização dos instrumentos de desenho, escalas, formatos e layout das folhas de desenho. Planejamento e elaboração de projetos adequados à diversidade humana, em especial para pessoas com alguma deficiência ou mobilidade reduzida. Utilizar os softwares de Desenho Digital como ferramenta técnica de comunicação, conforme as técnicas normalizadas pela ABNT.",
    },
    {
      id: 'eletromag',
      name: 'Eletromagnetismo Aplicado',
      sem: 4,
      cat: 'et_eletromag',
      prereqs: ["calc3","fis3"],
      codigo: 'AL0270',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Sistemas de coordenadas e operadores vetoriais. Campos eletromagnéticos harmônicos. Propriedades elétricas e magnéticas dos materiais. Equações de onda e suas soluções. Propagação de ondas eletromagnéticas e polarização. Introdução aos métodos numéricos em Eletromagnetismo.",
      objetivo: "Conhecer a teoria de campos eletromagnéticos em regime alternado, entender os fenômenos físicos relacionados e aplicar a teoria eletromagnética para a área de Telecomunicações.",
    },
    {
      id: 'fis_apl',
      name: 'Física Aplicada',
      sem: 4,
      cat: 'et_basico',
      prereqs: ["fis3"],
      codigo: 'AL0271',
      ch: '75h',
      ch_teo: 60,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Natureza e propagação da luz. Reflexão e refração. Óptica geométrica. Interferência. Difração. Convecção e radiação de calor. Estática.",
      objetivo: "Compreender a natureza e a propagação da luz, compreender os princípios de reflexão e refração da luz, entender a formação de imagens a partir de espelhos e lentes esféricas. Estudar os princípios de radiação e convecção de calor e os fundamentos de estática.",
    },
    {
      id: 'eq_dif2',
      name: 'Equações Diferenciais II',
      sem: 4,
      cat: 'et_basico',
      prereqs: ["eq_dif1"],
      codigo: 'AL0036',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Sequências e séries . Equações diferenciais lineares de coeficientes variáveis. Transformada de Laplace. Séries de Fourier. Equações diferenciais parciais.",
      objetivo: "Compreender soma infinita como extensão de soma finita e as noções de convergência e divergência. Resolver equações diferenciais ordinárias usando séries de potências e transformada de Laplace. Analisar os principais tipos de equações diferenciais parciais lineares de primeira e segunda ordem. Resolver equações diferenciais parciais de segunda ordem pelos métodos de separação de variáveis e de séries de Fourier.",
    },
    {
      id: 'sinais',
      name: 'Sinais e Sistemas',
      sem: 4,
      cat: 'et_sinais',
      prereqs: ["calc2"],
      codigo: 'AL0272',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Variáveis complexas, transformada de Laplace, série e transformada de Fourier, análise de sinais e sistemas.",
      objetivo: "Compreender e saber utilizar as ferramentas matemáticas básicas para a análise de sinais e sistemas analógicos de tempo contínuo. Compreender e analisar sinais e sistemas analógicos de tempo contínuo.",
    },
    {
      id: 'circ2',
      name: 'Circuitos Elétricos II',
      sem: 4,
      cat: 'et_eletronica',
      prereqs: ["circ1"],
      codigo: 'AL0414',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Senoides e fasores. Análise em regime estacionário senoidal. Análise de potência em corrente alternada. Circuitos trifásicos. Circuitos de acoplamento magnético. Introdução e aplicação da transformada de Laplace. Análise em frequência e diagrama de Bode. Simulação elétrica SPICE.",
      objetivo: "Equacionar, analisar e solucionar problemas compreendendo circuitos elétricos lineares em regime permanente senoidal através da transformada fasorial e da transformada de Laplace. Equacionar, analisar e solucionar problemas envolvendo circuitos elétricos trifásicos equilibrados. Modelar, analisar e solucionar problemas envolvendo circuitos elétricos interconectados através do método de análise de duas portas. Obter a função de transferência e analisar a resposta em frequência de circuitos RLC.",
    },
    {
      id: 'lab_c1',
      name: 'Laboratório de Circuitos Elétricos I',
      sem: 4,
      cat: 'et_eletronica',
      prereqs: ["circ_med","circ1"],
      codigo: 'AL0415',
      ch: '30h',
      ch_teo: 0,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Medidas elétricas. Fontes de tensão e corrente elétrica. Associações série e paralelo. Circuitos lineares invariantes no tempo. Circuitos de primeira ordem. Circuitos de segunda ordem.",
      objetivo: "Desenvolver e analisar experimentos práticos sobre os tópicos abordados na componente curricular de Circuitos Elétricos I.",
    },
    {
      id: 'calc_num',
      name: 'Cálculo Numérico',
      sem: 4,
      cat: 'et_computacao',
      prereqs: ["alg"],
      codigo: 'AL0037',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Erros. Zeros de Funções e Polinômios. Aproximações de Funções. Interpolação Numérica. Integração Numérica. Sistemas Lineares. Resolução numérica de equações diferenciais ordinárias. Apoio computacional.",
      objetivo: "Desenvolver noções sobre o funcionamento e uso de métodos numéricos básicos úteis para a resolução de problemas modelados por equações algébricas ou diferenciais.",
    },
    {
      id: 'ondas',
      name: 'Ondas e Linhas',
      sem: 5,
      cat: 'et_eletromag',
      prereqs: ["eletromag"],
      codigo: 'AL0307',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Reflexão e refração de ondas eletromagnéticas planas. Teoria das linhas de transmissão em altas frequências. Carta de Smith. Linhas de transmissão típicas. Guias de onda metálicos e dielétricos. Softwares de simulação eletromagnética.",
      objetivo: "Compreender os fenômenos de reflexão e refração das ondas eletromagnéticas nas interfaces entre os meios. Conhecer e analisar as topologias clássicas de linhas de transmissão e guias de onda.",
    },
    {
      id: 'fot',
      name: 'Dispositivos Fotônicos',
      sem: 5,
      cat: 'et_eletromag',
      prereqs: ["fis_apl"],
      codigo: 'AL2165',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Fibras ópticas e suas diferentes características, modos de propagação, atenuação e dispersão, tópicos de física de semicondutores, diodo emissor de luz e diodo laser. Princípios físicos dos fotodetectores, splitters, componentes WDM e amplificadores ópticos.",
      objetivo: "Entender os princípios físicos que regem os dispositivos ativos e passivos essenciais que compõem um sistema de comunicações ópticas, destacando as diferentes fontes, os fotodetectores, amplificadores, WDM e a fibra óptica. Compreender as interações entre os dispositivos fotônicos e seus efeitos positivos e negativos para o estabelecimento das comunicações ópticas.",
    },
    {
      id: 'proc_est',
      name: 'Processos Estocásticos',
      sem: 5,
      cat: 'et_sinais',
      prereqs: ["calc2","probest"],
      codigo: 'AL0308',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Revisão sobre modelos probabilísticos, experimentos e variáveis aleatórias, vetores aleatórios, estimação de uma variável aleatória, processos estocásticos, processamento de sinais aleatórios.",
      objetivo: "Compreender modelos de probabilidades, variáveis aleatórias e processos estocásticos, aplicando o conhecimento à estimação e modelagem de variáveis e processos aleatórios, capacitando o aluno para o desenvolvimento de seu conhecimento na área de processamento de sinais.",
    },
    {
      id: 'sist_com1',
      name: 'Sistemas de Comunicação I',
      sem: 5,
      cat: 'et_sinais',
      prereqs: ["sinais"],
      codigo: 'AL0310',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Revisão da Transformada de Fourier, densidade espectral, modulação em amplitude, modulação angular, multiplexação, análise de desempenho de modulações analógicas, amostragem de sinais e taxa de Nyquist.",
      objetivo: "Compreender e aplicar as técnicas de Modulação e Transmissão de Sinais, dando ênfase às suas aplicações em telecomunicações.",
    },
    {
      id: 'so',
      name: 'Sistemas Operacionais',
      sem: 5,
      cat: 'et_computacao',
      prereqs: ["alg"],
      codigo: 'AL0341',
      ch: '30h',
      ch_teo: 30,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução aos sistemas operacionais. Gerenciamento de processos. Gerenciamento de memória. Gerenciamento de E/S. Sistemas de arquivos.",
      objetivo: "Analisar os aspectos fundamentais da estrutura e do funcionamento de sistemas operacionais.",
    },
    {
      id: 'lab_c2',
      name: 'Laboratório de Circuitos Elétricos II',
      sem: 5,
      cat: 'et_eletronica',
      prereqs: ["circ2","lab_c1"],
      codigo: 'AL0418',
      ch: '30h',
      ch_teo: 0,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Geração e análise de formas de onda alternada. Medidas de tensão, corrente e potência CA. Ensaio de transformadores a vazio, com carga e curto-circuito. Circuitos acoplados magneticamente. Quadripolos. Circuitos polifásicos. Medida de resposta em frequência de circuitos RC, RL e RLC.",
      objetivo: "Desenvolver e analisar experimentos práticos sobre os tópicos abordados na componente curricular de Circuitos Elétricos II.",
    },
    {
      id: 'circ_el1',
      name: 'Circuitos Eletrônicos I',
      sem: 5,
      cat: 'et_eletronica',
      prereqs: ["circ1"],
      codigo: 'AL0419',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução aos materiais semicondutores e física dos semicondutores, correntes de deriva e difusão, e junção PN. Construção, princípio de funcionamento, curvas de tensão e corrente, e modelo de pequenos sinais de dispositivos semicondutores: Diodos (de junção, zener, varactor, PIN, Schottky e Fotodiodo), Transistores de Efeito de Campo (JFET, MOSFET, HEMT e FINFET) e Transistores Bipolares de Junção (BJT). Amplificador operacional ideal e suas aplicações. Simulação Elétrica SPICE.",
      objetivo: "Compreender os conceitos básicos da física dos semicondutores, os principais dispositivos semicondutores utilizados em sistemas eletrônicos de telecomunicações e o amplificador operacional ideal.",
    },
    {
      id: 'microond',
      name: 'Micro-ondas',
      sem: 6,
      cat: 'et_eletromag',
      prereqs: ["ondas"],
      codigo: 'AL0315',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Teoria circuital para sistemas de micro-ondas: matrizes Z, Y, S e ABCD. Técnicas de casamento de impedâncias. Divisores de potência e acopladores direcionais. Filtros passivos em micro-ondas. Introdução à análise de sistemas operando em micro-ondas.",
      objetivo: "Analisar dispositivos e sistemas operando em micro-ondas utilizando matrizes equivalentes Z, Y, S e ABCD. Compreender e estudar as principais técnicas de casamento de impedâncias. Aprender a projetar filtros passivos, divisores de potência e acopladores direcionais operando em micro-ndas.",
    },
    {
      id: 'sist_com2',
      name: 'Sistemas de Comunicação II',
      sem: 6,
      cat: 'et_sinais',
      prereqs: ["sist_com1"],
      codigo: 'AL0313',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Análise de espaço de sinais, sinais aleatórios e ruído, transmissão de dados em banda base, técnicas de modulações digitais em banda passante, análise de desempenho de sistemas de comunicações digitais, espalhamento espectral, modulação multiportadora, sincronização, equalização.",
      objetivo: "Compreender e aplicar as técnicas de modulação e transmissão de sinais digitais, dando ênfase às suas aplicações em telecomunicações, além de abordar tópicos mais recentes na área.",
    },
    {
      id: 'pds1',
      name: 'Processamento Digital de Sinais I',
      sem: 6,
      cat: 'et_sinais',
      prereqs: ["sinais"],
      codigo: 'AL0420',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Análise de sistemas em tempo discreto, transformada Z, análise de Fourier de sinais em tempo discreto, introdução ao processamento digital de sinais, conceitos de filtragem, filtros digitais: FIR e IIR.",
      objetivo: "Compreender e saber utilizar as ferramentas matemáticas básicas para a análise de sinais e sistemas digitais de tempo discreto. Compreender e analisar os fundamentos do processamento digital de sinais.",
    },
    {
      id: 'redes_com',
      name: 'Redes de Comunicação',
      sem: 6,
      cat: 'et_computacao',
      prereqs: ["so"],
      codigo: 'AL0309',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução a redes de comunicação. Estrutura e topologias de redes. Camada de rede. Camada de transporte. Camada de aplicação. Camada Física. Camada de Enlace de Dados. Camada de Acesso ao Meio. Segurança em Redes.",
      objetivo: "Conhecer os detalhes de implementações de redes de comunicação. Reconhecer e aplicar formas de distribuição da informação e dos protocolos de acesso à redes de comunicação.",
    },
    {
      id: 'circ_el2',
      name: 'Circuitos Eletrônicos II',
      sem: 6,
      cat: 'et_eletronica',
      prereqs: ["circ_el1","lab_c2"],
      codigo: 'AL0421',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução aos amplificadores: Impedância de entrada e saída, ganho de tensão e corrente, efeito da impedância de fonte e de carga, e conversão CC-CA. Circuitos amplificadores com transistores bipolar e de efeito de campo: Polarização CC e modelo de pequenos sinais. Resposta em frequência. Ruído em circuitos amplificadores. Amplificadores de múltiplos estágios: Cascata e cascode. Amplificador de potência: Classes de operação, eficiência e linearidade, e conexões com múltiplos transistores. Simulação elétrica SPICE.",
      objetivo: "Compreender a modelagem em pequenos sinais, o comportamento no domínio da frequência, a análise do ruído e o projeto de circuitos amplificadores com transistores bipolares e de efeito de campo.",
    },
    {
      id: 'com_opt',
      name: 'Comunicações Ópticas',
      sem: 6,
      cat: 'et_eletromag',
      prereqs: ["fot"],
      codigo: 'AL0322',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução às comunicações ópticas. Enlaces ópticos analógicos e digitais. Penalidades de potência, tempo de subida, OSNR, BER. Estruturação das redes ópticas avançadas (Metrocore, Regional e Backbone). Redes ópticas de acesso (PON). Medidas e monitoramento de desempenho de redes ópticas.",
      objetivo: "Aprender a dimensionar e verificar/homologar a qualidade de comunicação nos enlaces ópticos analógicos e digitais. Compreender a origem das penalidades de potência e tempo de subida dos enlaces ópticos e como elas afetam as métricas de qualidade de comunicação OSNR e BER. Compreender e dimensionar redes ópticas passivas de acesso. Compreender e projetar as redes ópticas avançadas e de mais alta hierarquia com dispositivos ativos, com sistemas SDH/Sonet.",
    },
    {
      id: 'inst_el',
      name: 'Instalações Elétricas Prediais',
      sem: 6,
      cat: 'et_eletronica',
      prereqs: ["circ2"],
      codigo: 'AL0081',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Projeto de instalações elétricas prediais: definições, simbologia, localização de cargas elétricas, quadro de cargas, dimensionamento de eletrodutos e condutores, luminotécnico, proteção contra sobrecargas, curtos-circuitos e descargas atmosféricas. Desenho auxiliado por computador. Projeto de instalações telefônicas: definições, simbologia, esquemas e dimensionamento de tubulações e cabos (entrada, primária e secundária). Rede interna: distribuição e blocos terminais.",
      objetivo: "Dimensionar e projetar sistemas de instalações elétricas, de força, iluminação e telefonia, nos níveis residenciais e prediais.",
    },
    {
      id: 'ext2',
      name: 'Extensão II',
      sem: 6,
      cat: 'et_basico',
      prereqs: ["ext1"],
      codigo: 'AL0422',
      ch: '60h',
      ch_teo: 0,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 60,
      ementa: "Desenvolvimento de atividades previstas nos projetos de extensão universitária da Unipampa em âmbito local e nacional. As áreas temáticas de atuação no curso são: Eletromagnetismo Aplicado, Sinais e Sistemas, Eletrônica ou Computação.",
      objetivo: "Colaborar em projetos de extensão universitária da Unipampa.",
    },
    {
      id: 'antenas',
      name: 'Antenas',
      sem: 7,
      cat: 'et_eletromag',
      prereqs: ["ondas"],
      codigo: 'AL0316',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução à teoria de antenas. Características e propriedades elétricas das antenas. Estudo de irradiadores filamentares. Teoria das redes lineares e impedância mútua. Antenas com refletores. Antenas de microfita.",
      objetivo: "Adquirir conceitos básicos sobre análise de irradiadores simples, tais como antenas filamentares, redes de antenas, antenas com refletores e antenas de microfita. Conhecer os princípios básicos de funcionamento de antenas simples. Analisar sistemas de telecomunicações, do ponto de vista de sistemas irradiantes.",
    },
    {
      id: 'sist_com3',
      name: 'Sistemas de Comunicação III',
      sem: 7,
      cat: 'et_sinais',
      prereqs: ["sist_com1"],
      codigo: 'AL0318',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Teoria da informação, codificação de fonte, compactação de dados, ruído e capacidade de canal, códigos corretores de erros, códigos de bloco, códigos convolucionais, códigos modernos.",
      objetivo: "Compreender e manipular sistemas de comunicação digital. Compreender e manipular esquemas de compactação e codificação de dados para transmissão através de canais com ruído.",
    },
    {
      id: 'sist_dist',
      name: 'Fundamentos de Sistemas Distribuídos',
      sem: 7,
      cat: 'et_computacao',
      prereqs: ["redes_com"],
      codigo: 'AL0423',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Fundamentos de Sistemas Distribuídos. Caracterização de sistemas distribuídos para Telecomunicações. Comunicação e Sincronização entre processos. Gerência de Processos distribuídos. Segurança em Telecomunicações. Sistemas Multimídia Distribuídos.",
      objetivo: "Compreender a estrutura e o funcionamento básico de sistemas e algoritmos distribuídos, considerando os aspectos de comunicação, sincronização, confiabilidade e escalabilidade.",
    },
    {
      id: 'el_inst',
      name: 'Eletrônica Aplicada e Instrumentação',
      sem: 7,
      cat: 'et_eletronica',
      prereqs: ["circ_el2"],
      codigo: 'AL0059',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução. O amplificador operacional. Sensores. Aquisição de dados.",
      objetivo: "Compreender o funcionamento geral e a aplicação dos sistemas de instrumentação eletrônica e aquisição de dados, bem como as grandezas físicas, sensores e transdutores elétricos.",
    },
    {
      id: 'circ_el3',
      name: 'Circuitos Eletrônicos III',
      sem: 7,
      cat: 'et_eletronica',
      prereqs: ["circ_el2"],
      codigo: 'AL0424',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Amplificadores sintonizados: topologias, impedância de entrada e saída, e largura de banda. Introdução a circuitos osciladores: realimentação e estabilidade, e ruído de fase. Topologias de circuitos osciladores: deslocamento de fase, sintonizado, cristal e astável. Osciladores controlados por tensão e circuitos de controle automático de frequência. Circuitos de conversão de frequência passivos e ativos. Simulação elétrica SPICE.",
      objetivo: "Compreender a modelagem e o projeto de circuitos amplificadores sintonizados, circuitos realimentados, osciladores e circuitos de conversão de frequência.",
    },
    {
      id: 'pds2',
      name: 'Processamento Digital de Sinais II',
      sem: 7,
      cat: 'et_sinais',
      prereqs: ["pds1"],
      codigo: 'AL0425',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Revisão de processamento digital de sinais, projeto de filtros digitais FIR e IIR, aplicações de filtros digitais a processamento de sinais.",
      objetivo: "Compreender e analisar projetos de filtros digitais FIR e IIR. Aplicar o conhecimento em aplicações específicas na área de processamento digital de sinais.",
    },
    {
      id: 'eng_eco',
      name: 'Introdução à Engenharia Econômica',
      sem: 7,
      cat: 'et_basico',
      prereqs: ["probest"],
      codigo: 'AL0380',
      ch: '45h',
      ch_teo: 15,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Fundamentos da matemática financeira. Análise de viabilidade econômica de projetos de investimentos.",
      objetivo: "Obter conhecimentos, do campo da engenharia econômica, para possibilitar a adequada tomada de decisão na análise de projetos de investimentos.",
    },
    {
      id: 'ext3',
      name: 'Extensão III',
      sem: 7,
      cat: 'et_basico',
      prereqs: ["ext2"],
      codigo: 'AL0426',
      ch: '60h',
      ch_teo: 0,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 60,
      ementa: "Desenvolvimento de atividades previstas nos projetos de extensão universitária do curso de Engenharia de Telecomunicações e áreas afins. As áreas temáticas de atuação no curso são: Eletromagnetismo Aplicado, Sinais e Sistemas, Eletrônica ou Computação.",
      objetivo: "Colaborar em projetos de extensão na área de Engenharia de Telecomunicações ou afins.",
    },
    {
      id: 'circ_mw',
      name: 'Circuitos Ativos em Micro-ondas',
      sem: 8,
      cat: 'et_eletromag',
      prereqs: ["microond"],
      codigo: 'AL0320',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Modelo de resistores, capacitores e indutores para alta frequência. Modelo de dispositivos semicondutores em alta frequência. Introdução à análise de sistemas operando em micro-ondas. Projeto de circuitos amplificadores, osciladores e conversores de frequência em micro-ondas. Técnicas de leiaute para micro-ondas. Softwares de simulação eletromagnética.",
      objetivo: "Compreender e projetar circuitos eletrônicos ativos na faixa de micro-ondas.",
    },
    {
      id: 'prop',
      name: 'Propagação',
      sem: 8,
      cat: 'et_eletromag',
      prereqs: ["ondas"],
      codigo: 'AL0317',
      ch: '60h',
      ch_teo: 60,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Características básicas dos sistemas de radiocomunicação. Propagação no espaço livre. Propagação na troposfera. Difração em obstáculos naturais. Radio-enlaces com desvanecimento. Propagação em pequena escala. Propriedades dos meios anisotrópicos. Ondas Ionosféricas e ondas de superfície. Radio-enlaces via satélite.",
      objetivo: "Entender os princípios da propagação de ondas eletromagnéticas e como os fenômenos atmosféricos influenciam as radiocomunicações. Projetar e analisar radioenlaces terrestres (grande e pequena escala), considerando efeitos atmosféricos e geográficos, e enlaces de comunicação via satélite.",
    },
    {
      id: 'com_mov',
      name: 'Comunicações Móveis',
      sem: 8,
      cat: 'et_sinais',
      prereqs: ["sist_com2"],
      codigo: 'AL0321',
      ch: '30h',
      ch_teo: 30,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução e conceitos associados aos sistemas telefônicos, sinalização, centrais telefônicas, planejamento de tráfego e de sistemas telefônicos, introdução às redes móveis, conceitos e topologias da rede celular, evolução das redes móveis.",
      objetivo: "Entender o funcionamento básico da telefonia, desenvolvendo a habilidade de realizar o planejamento e dimensionamento de sistemas de comunicações. Compreender o funcionamento da telefonia móvel, além de aprender as técnicas mais recentemente utilizadas nesse meio.",
    },
    {
      id: 'proj_rf',
      name: 'Projeto de Receptores e Transmissores de RF',
      sem: 8,
      cat: 'et_eletronica',
      prereqs: ["circ_el3"],
      codigo: 'AL0427',
      ch: '60h',
      ch_teo: 30,
      ch_prat: 30,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Circuitos moduladores e demoduladores em amplitude, frequência e fase. Introdução aos circuitos transmissores e receptores de RF: padrões de comunicação, topologias, linearidade e sensibilidade. Projeto de circuitos receptores e controle automático de ganho. Projeto de transmissores. Simulação elétrica SPICE. Técnicas de leiaute de placa de circuito impresso em alta frequência.",
      objetivo: "Compreender a modelagem e o projeto de circuitos moduladores e demoduladores. Analisar, projetar e caracterizar circuitos receptores e transmissores de RF.",
    },
    {
      id: 'micro',
      name: 'Microcontroladores',
      sem: 8,
      cat: 'et_eletronica',
      prereqs: ["circ_el1"],
      codigo: 'AL0105',
      ch: '60h',
      ch_teo: 45,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Microarquitetura von Neumann e Harvard. Microinstruções e Microprograma. Estudo particularizado de um microprocessador/microcontrolador representativo: arquitetura, conjunto de instruções, registradores, sub-rotinas, interrupções, periféricos, programação em linguagem de alto nível e montagem (assembly) e aplicações. Outras famílias de microprocessadores e microcontroladores. Ambiente de programação.",
      objetivo: "Compreender a arquitetura e organização de microcontroladores. Implementar firmwares em linguagem de baixo nível e alto nível em microcontrolador específico. Utilizar e programar os periféricos disponíveis no microcontrolador. Realizar depuração e simulação de firmwares em ambiente computacional. Gravar firmwares em microcontroladores e realizar experimentos práticos.",
    },
    {
      id: 'proj_pesq',
      name: 'Projeto de Pesquisa e Desenvolvimento',
      sem: 8,
      cat: 'et_outras',
      prereqs: [],
      specialMinCH: 2457,
      codigo: 'AL0144',
      ch: '45h',
      ch_teo: 30,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Métodos científicos, pesquisa bibliográfica, normalização de trabalhos científicos. Gerenciamento de projetos: conceitos, planejamento, execução, controle e ações. Análise de viabilidade econômica. Elaboração da proposta do Trabalho de Conclusão de Curso (TCC).",
      objetivo: "Planejar e executar utilizando metodologia científica um projeto de pesquisa sob orientação de um(a) professor(a) orientador(a) que culmine em uma proposta de Trabalho de Conclusão de Curso, redigida de acordo com a normativa vigente para formatação de trabalhos acadêmicos.",
    },
    {
      id: 'adm',
      name: 'Administração',
      sem: 8,
      cat: 'et_basico',
      prereqs: ["eng_eco"],
      codigo: 'AL0394',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Fundamentos da administração. O administrador. Partes da administração. Planejamento da ação empresarial.",
      objetivo: "Entender a natureza da gestão empresarial e os sistemas produtivos; conhecer técnicas e metodologias administrativas que podem ser aplicadas na gestão e na tomada de decisão diante da produção de bens e execução de serviços.",
    },
    {
      id: 'tcc',
      name: 'Trabalho de Conclusão de Curso',
      sem: 9,
      cat: 'et_outras',
      prereqs: ["proj_pesq"],
      codigo: 'AL0155',
      ch: '60h',
      ch_teo: 0,
      ch_prat: 60,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Elaboração de um trabalho de conclusão de curso voltado para atividades de complementação profissional, desenvolvido sob orientação de um professor do curso.",
      objetivo: "Realizar uma síntese dos conhecimentos e habilidades adquiridas ao longo do curso. Elaborar trabalho de conclusão de curso com base em metodologia científica. Apresentar trabalho de conclusão de curso para a banca de avaliação.",
    },
    {
      id: 'leg_et',
      name: 'Legislação, Ética e Exercício Profissional de Engenharia',
      sem: 9,
      cat: 'et_basico',
      prereqs: [],
      codigo: 'AL0142',
      ch: '30h',
      ch_teo: 30,
      ch_prat: 0,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Fundamentos e conceituação filosófica de moral, ética e valores. Ética no ambiente de trabalho. Sistema CONFEA/CREAs. Legislação Profissional - CONFEA/CREAs. Código de Ética Profissional do engenheiro. Legislação Profissional - CONFEA/CREAs. Responsabilidade Técnica - Código de Defesa do Consumidor. Propriedade Intelectual. Direitos Autorais. Transferência de tecnologia-concorrência desleal - abuso de poder econômico. Acervo técnico. Atribuições profissionais.",
      objetivo: "Conhecer acerca das responsabilidades técnicas e civis, numa perspectiva da ética e do exercício profissional no papel de sujeitos participantes das mudanças socioeconômicas.",
    },
    {
      id: 'empreend',
      name: 'Empreendedorismo',
      sem: 9,
      cat: 'et_basico',
      prereqs: ["adm"],
      codigo: 'AL0402',
      ch: '30h',
      ch_teo: 15,
      ch_prat: 15,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Introdução ao empreendedorismo. Processo empreendedor. Entendendo a expansão do negócio.",
      objetivo: "Adquirir conhecimentos a respeito da criação de negócios e desenvolver a cultura empreendedora.",
    },
    {
      id: 'cccg1',
      name: 'CCCG',
      sem: 9,
      cat: 'et_outras',
      prereqs: [],
      codigo: '',
      ch: '60h',
      ementa: CCCG_EMENTA,
    },
    {
      id: 'cccg2',
      name: 'CCCG',
      sem: 9,
      cat: 'et_outras',
      prereqs: [],
      codigo: '',
      ch: '60h',
      ementa: CCCG_EMENTA,
    },
    {
      id: 'estagio',
      name: 'Estágio Supervisionado para a Engenharia de Telecomunicações',
      sem: 10,
      cat: 'et_outras',
      prereqs: [],
      specialMinCH: 2808,
      codigo: 'AL0448',
      ch: '165h',
      ch_teo: 0,
      ch_prat: 165,
      ch_ead_t: 0,
      ch_ead_p: 0,
      ch_ext: 0,
      ementa: "Estágio Curricular Supervisionado Obrigatório em instituições, empresas públicas civis ou militares, autárquicas, privadas e de economia mista. O estágio deve ser na área do cursou área afim, sob orientação técnica de um professor e sob supervisão de um engenheiro da empresa.",
      objetivo: "Obter experiências pré-profissionais que possibilitam a identificação de experiências de atuação em campos de futuras atividades profissionais, bem como, ampliar o interesse pela pesquisa técnica e científica relacionada com os problemas peculiares relacionados ao curso; participar no processo de integração Universidade-Empresa que possibilite a transferência de tecnologia, bem como, a obtenção de subsídios que permitem a adequação do currículo às exigências do mercado.",
    },
  ];

  window.GRADE_CURSO_CONFIG = {
    sigla: 'et',
    title: "Grade Curricular \u2014 Engenharia de Telecomunica\u00e7\u00f5es",
    subtitle: "UNIPAMPA \u00b7 Campus Alegrete \u00b7 PPC vigente",
    maxSemesters: 10,
    disciplines,
    /** Plano de integralização (PPC: Tabela 1). */
    chIntegralization: {
      total: 3930,
      buckets: [
        {
          id: 'ccog',
          shortLabel: 'CCOG',
          label: 'Componentes curriculares obrigatórios de graduação (CCOGs)',
          required: 3510,
          source: 'mandatory',
        },
        {
          id: 'cccg',
          shortLabel: 'CCCG',
          label: 'Componentes curriculares complementares de graduação (CCCGs)',
          required: 120,
          source: 'cccg',
        },
        {
          id: 'acev',
          shortLabel: 'ACEV',
          label: 'Atividades curriculares de extensão vinculadas (ACEV)',
          required: 165,
          source: 'aceMandatory',
          countsTowardTotal: false,
        },
        {
          id: 'acee',
          shortLabel: 'ACEE',
          label: 'Atividades curriculares de extensão específicas (ACEE)',
          required: 240,
          manual: true,
        },
        {
          id: 'acg',
          shortLabel: 'ACG',
          label: 'Atividades complementares de graduação (ACGs)',
          required: 60,
          manual: true,
        },
      ],
    },
    cccgSemLimits: {
      9: 120,
    },
    cccgs: [
      {
        codigo: "AL2062",
        nome: "Introdução à Programação com MATLAB",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: ["alg"],
        ementa: "Introdução ao MATLAB. O ambiente de programação MATLAB. Programação básica com MATLAB. Depuração com MATLAB. Estruturas de repetição. Funções definidas pelo usuário. Plotando e programando gráficos com MATLAB.",
        objetivo: "Este componente curricular objetiva descrever os conceitos básicos da programação com Matlab para o desenvolvimento de funções simples e complexas. É prevista a utilização de bibliotecas extras para auxiliar no desenvolvimento de algumas soluções a serem implementadas. Durante todo o componente curricular de forma a inserir tais conceitos e técnicas em um contexto prático, isto é, com exemplos marcantes e não apenas com palavras.",
      },
      {
        codigo: "AL2140",
        nome: "Processamento Adaptativo de Sinais",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Revisão de processos estocásticos e Filtros digitais. Introdução a filtragem adaptativa. Estruturas de filtros. Filtro de Wiener. Filtros FIR adaptativos: algoritmos LMS e derivados; algoritmos RLS e derivados. Filtros IIR adaptativos. Aplicações práticas.",
        objetivo: "Compreender e analisar os princípios da filtragem adaptativa, estudando as estruturas de filtros digitais e algoritmos de adaptação. Estudar e incentivar aplicações práticas de sistemas de filtragem adaptativa.",
      },
      {
        codigo: "AL2133",
        nome: "Projeto de Circuitos Integrados Analógicos I",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Estrutura e funcionamento do transistor MOS. Modelos matemáticos do transistor: região linear, região de saturação e região sub-limiar. Modelo de pequenos sinais. Efeitos de segunda ordem no modelo de pequenos sinais: modulação de canal, efeito de corpo. Comportamento em frequência. Estágios de amplificação: fonte comum, seguidor de fonte, gate comum, cascode e estágio diferencial. Comportamento, simulação e análise de curvas típicas. Circuitos de polarização: cargas MOS, referências de tensão e espelhos de corrente. Amplificadores operacionais: características gerais, amplificadores de um estágio e amplificadores de dois estágios. Extração das especificações do circuito através de simulação elétrica. Estudo de caso: projeto e simulação de amplificadores operacionais e de transcondutância.",
        objetivo: "Obter conhecimentos e habilidades sobre os fundamentos de projeto de circuitos integrados analógicos e utilização de ferramentas de CAD para microeletrônica. Aprender e exercitar as etapas do fluxo de projeto de circuitos integrados analógicos: especificação, simulação, leiaute, verificação e teste. Aprender a projetar circuitos amplificadores integrados em tecnologia CMOS.",
      },
      {
        codigo: "AL2202",
        nome: "Projeto de Conversores de Dados Integrados",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Revisão sobre os fundamentos de conversão analógico-digital (AD) e digital-analógico (DA): Teoria da amostragem, critério de Nyquist, aliasing, ruído de quantização, e conversores AD e DA ideais. Parâmetros e limitações de ADCs e DACs. Topologias de conversores AD do tipo Nyquist: Integrador, Integrador Dupla-Rampa, Flash, SAR e Pipeline. Topologias de conversores AD sobreamostrados: moduladores sigma-delta em tempo discreto e tempo contínuo. Conversores DA: DACs resistivos, DACs current steering e DACs capacitivos. Estudo de caso: projeto de conversores AD e DA em tecnologia CMOS.",
        objetivo: "Conhecer os fundamentos de projeto de conversores de dados integrados. Aprender e exercitar as etapas do fluxo de projeto de circuitos integrados analógicos e de sinais mistos: especificação, simulação, leiaute, verificação e teste. Aprender a projetar circuitos analógicos e circuitos digitais de controle integrados em tecnologia CMOS.",
      },
      {
        codigo: "AL2149",
        nome: "Prototipação de Sistemas Digitais",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 30,
        ch_prat: 30,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Conceitos básicos de semicondutores. Famílias lógicas: TTL, ECL, MOS, CMOS. Estilos de projetos: Circuitos Integrados de Aplicações Específicas (ASIC) e Dispositivos Lógicos Programáveis (CPLDs e FPGAs). Metodologias de projeto: bottom-up e top-down. Linguagens de Descrição de Hardware (HDL): Verilog, System Verilog e VHDL. Estudo particularizado de uma linguagem HDL. Especificação, projeto, verificação e implementação de circuitos combinacionais, sequenciais e máquina de estados em FPGA.",
        objetivo: "Especificar, projetar, verificar e implementar circuitos digitais com o uso de dispositivos programáveis e linguagem de descrição de hardware.",
      },
      {
        codigo: "AL2150",
        nome: "Técnicas de Diversidade em Sistemas de Comunicação",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Conceitos de sistemas de comunicação digital. Diversidade na recepção de sinais. Diversidade na transmissão de sinais. Códigos de bloco espaço-temporais. Orthogonal Frequency-Division Multiplexing (OFDM). Multiple Input Multiple Output (MIMO) para sistemas OFDM. Comunicações cooperativas.",
        objetivo: "Entender o conceito de diversidade para sistemas de comunicação, desenvolvendo noções de análise, modelagem e aplicação das principais técnicas relacionadas ao conceito.",
      },
      {
        codigo: "AL2139",
        nome: "TV Digital",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 60,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Meios de Transmissão (Terrestre, Cabo e Satélite) Sistemas e Padrões de TV Digital (DVB, ISDB, ATSC, DTMB e SBTVD), TV Digital Móvel: WEBTV, MobileTV (Vídeo sob demanda, Streaming de vídeo). Codificação e Decodificação de Vídeo Digital: Normatização, Estimação e Compensação de Movimento, Quantização, Transformadas, Entropia, Containers.",
        objetivo: "Conhecer os diferentes sistemas de codificação, processamento e transmissão de vídeos relativos à TV Digital. Descrever técnicas para processamento, codificação/decodificação e transmissão de sinais de TV Digital.",
      },
      {
        codigo: "AL2183",
        nome: "Infraestrutura e Projeto de Redes de Comunicação",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Cabeamento Estruturado. Metodologia Top-Down no projeto de Redes.Projeto de Rede Lógica (NAT, DMZ, VLAN e VPN). Projeto de Rede Física (WAN e LAN). Dimensionamento de cargas e Conceitos de Termodinâmica. Especificações e Documentação.",
        objetivo: "Analisar dispositivos e sistemas para o desenvolvimento de projetos de rede local com infraestrutura de pequenas e grandes dimensões incluindo redes com interligação predial de LANs matriz/filial. Analisar e desenvolver interligação de redes remotas com plano de contingência utilizando tecnologias de internet como VPN.",
      },
      {
        codigo: "AL2240",
        nome: "Libras I",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 0,
        ch_prat: 0,
        ch_ead_t: 15,
        ch_ead_p: 45,
        ch_ext: 0,
        prereqs: [],
        ementa: "Fundamentos linguísticos e culturais da Língua Brasileira de Sinais. Habilidades básicas expressivas e receptivas em Libras. Introdução aos Estudos Surdos.",
        objetivo: "Desenvolver as habilidades de recepção e de produção sinalizada, visando ao desenvolvimento da competência discursiva da Língua Brasileira de Sinais.",
      },
      {
        codigo: "AL2241",
        nome: "Libras II",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 0,
        ch_prat: 0,
        ch_ead_t: 15,
        ch_ead_p: 45,
        ch_ext: 0,
        prereqs: [],
        ementa: "Aprimoramento das estruturas da Libras. Aperfeiçoamento da compreensão e produção em nível intermediário. Prática do uso da Libras em situações discursivas formais e informais (roleplay). Escrita de Sinais.",
        objetivo: "Aprofundar os conhecimentos relacionados à competência discursiva no uso da Libras, articulando teoria e prática, a fim de possibilitar a seus usuários a comunicação em Libras de forma contextualizada.",
      },
      {
        codigo: "AL0430",
        nome: "Sistemas de Controle I",
        cat: 'et_outras',
        ch: 60,
        ch_teo: 45,
        ch_prat: 15,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Introdução aos sistemas de controle. Modelagem matemática de sistemas dinâmicos. Resposta no tempo de sistemas de controle com retroação. Estabilidade de sistemas lineares com retroação. Erros de Regime Permanente. Construção do Lugar das Raízes. Análise pela resposta em frequência. Estabilidade no domínio da frequência. Introdução aos sistemas de controle digital. Modelagem e análise de sistemas de controle digital.",
        objetivo: "Realizar a modelagem contínua de sistemas físicos. Analisar sistemas de controle contínuos e discretos no tempo. Reconhecer as relações entre comportamento de sistemas de controle no tempo e no domínio da frequência.",
      },
      {
        codigo: "AL2144",
        nome: "Relações Étnico-raciais",
        cat: 'et_outras',
        ch: 30,
        ch_teo: 30,
        ch_prat: 0,
        ch_ead_t: 0,
        ch_ead_p: 0,
        ch_ext: 0,
        prereqs: [],
        ementa: "Tratar os conceitos de etnia, raça, racialização, identidade, diversidade, diferença. Compreender os grupos étnicos “minoritários” e processos de colonização e pós-colonização. Políticas afirmativas para populações étnicas e políticas afirmativas específicas em educação. Populações étnicas e diásporas. Racismo, discriminação e perspectiva didático-pedagógica de educação antirracista. Currículo e política curriculares. História e cultura étnica na escola e itinerários pedagógicos. Etnia/Raça e a indissociabilidade de outras categorias da diferença. Cultura e hibridismo culturais. As etnociências na sala de aula. Movimentos Sociais e educação não formal. Pesquisas em educação no campo da educação e relações étnico-raciais.",
        objetivo: "Pensar o“outro”, o diferente, percebendo a complexidade de outras formações culturais e entendendo outras práticas culturais dentro de uma lógica própria, partindo de seus próprios parâmetros, construindo desta forma, uma percepção de que a nossa cultura é apenas uma das formas possíveis de perceber e interpretar o mundo e que todas as culturas são igualmente válidas e fazem sentido para seus participantes.",
      },
    ],
  };
})();
